import { StrategyDefinition } from '../../../types.ts';

/**
 * STRATEGY LIBRARY V2.0 - POSITION STRATEGIES (中长线持仓模型)
 * Target Holding Period: 1 - 12 Months (季度再平衡或长期复利)
 * Evidence Base: Fama-French multi-factor asset pricing, AQR QMJ, Piotroski F-Score, Novy-Marx, and Minervini Stage 2.
 * Count: Exactly 24 models.
 */

export const POSITION_MODELS: StrategyDefinition[] = [
  // 1. Jegadeesh & Titman 6-12M Cross-Sectional Momentum
  {
    id: 'jt_momentum',
    slug: 'jegadeesh-titman-cross-sectional-momentum',
    name: 'Jegadeesh & Titman Cross-Sectional Momentum',
    nameZh: '经典 6-12 个月截面动量',
    nameEn: 'Jegadeesh & Titman Cross-Sectional Momentum Factor',
    shortName: 'JT截面动量',
    mode: 'POSITION',
    holdingPeriod: '1-6 Months',
    holdingPeriodLabel: '中期 1-6月',
    strategyFamily: 'Cross-Sectional Momentum',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '1-6 Months',
    direction: 'LONG',
    author: 'Narasimhan Jegadeesh & Sheridan Titman',
    origin: 'The Journal of Finance (1993)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_jegadeesh_titman_1993'],
    sourceReference: 'Jegadeesh, Narasimhan, and Sheridan Titman. Returns to Buying Winners and Selling Losers. The Journal of Finance 48.1 (1993): 65-91.',
    thesis: '在美股截面上，过去 6 至 12 个月收益率位于前 10% 的赢家组合，在未来 3-12 个月由于机构知情交易者持续买入与投资者渐进反应，具备显著超越市场的动量溢价。',
    description: '量化金融经典文献。筛选全市场中期相对强度排名前 10% 标的，规避近 1 个月反转影响，长周期持有。',
    requiredData: ['DAILY_OHLCV', 'MOMENTUM_12M_EX_1M'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [
      { id: 'distTolerance', name: '距52周新高容忍(%)', type: 'number', default: -10, min: -25, max: -3, step: 1, description: '维持高位相对强度' }
    ],
    rules: {
      type: 'group',
      id: 'jt_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'jt_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -10, label: '维持在历史强势位 (距高点 < 10%)' },
        { type: 'leaf', id: 'jt_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '多头趋势稳健运行 (> 0.2%)' },
        { type: 'leaf', id: 'jt_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛机构流动性 (RVOL >= 1.0x)' }
      ]
    },
    entry: ['过去 12 个月累计回报位于全市场前 10%', '股价距离 52 周新高小于 10%', '位于 200 日均线上方'],
    confirmation: ['月末定期再平衡'],
    exit: ['相对强度跌出全市场前 30% 分位平仓，或月线有效跌破 200 日均线'],
    rebalance: ['按月度或季度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '跌破 50 日均线下穿 200 日均线 (Death Cross) 或单股最大回撤 8% 截断', profitTargetRule: '定期再平衡让赢家持仓充分复利', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 126 },
    antiLookaheadRules: ['月末收盘后计算截面排名，次月第一个交易日开盘调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Jegadeesh & Titman (1993) JF',
      empiricalFindings: 'Documented 12.01% annualized excess return for 6/6 momentum strategies across US equities from 1965 to 1989.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['中长线', '学术A+', '截面动量', '因子选股', '动量效应'],
    version: '2.0.0'
  },

  // 2. Fama-French Size & Momentum Quality Composite
  {
    id: 'fama_french_size_mom',
    slug: 'fama-french-size-momentum-composite',
    name: 'Fama-French Size & Momentum Quality Composite',
    nameZh: '规模与动量双因子优选',
    nameEn: 'Fama-French Size & Momentum Quality Composite',
    shortName: 'FF规模动量复合',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Multi-Factor',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Eugene Fama & Kenneth French',
    origin: 'Journal of Financial Economics (1993)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_fama_french_1992', 'src_carhart_1997'],
    sourceReference: 'Fama, Eugene F., and Kenneth R. French. Common Risk Factors in the Returns on Stocks and Bonds. JFE 33.1 (1993): 3-56.',
    thesis: '中小盘股具备较高的长期成长弹性，叠加跨截面高动量过滤，能够规避陷入中小盘价值陷阱，大幅提升资产定价组合的复合夏普比率。',
    description: '结合规模因子 (SMB) 与动量因子 (WML) 的长周期基本面量化持仓模型。',
    requiredData: ['DAILY_OHLCV', 'MARKET_CAP', 'SMA_200'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [
      { id: 'minCap', name: '最低市值 ($B)', type: 'number', default: 2.0, min: 0.5, max: 20.0, step: 0.5, description: '过滤微小盘流动性风险' }
    ],
    rules: {
      type: 'group',
      id: 'ff_sm_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ff_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '保持在中高位动能通道 (距高点 < 15%)' },
        { type: 'leaf', id: 'ff_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '稳健上行阳线 (> 0.2%)' },
        { type: 'leaf', id: 'ff_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛机构换手 (RVOL >= 1.0x)' }
      ]
    },
    entry: ['市值在 20 亿至 300 亿美元优质区间', '近 12 个月动量位于前 20%', '运行在 200 日均线上方'],
    confirmation: ['季度定期再平衡入场'],
    exit: ['跌破 200 日均线或动量恶化平仓'],
    rebalance: ['按季度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 移动跟踪止损', profitTargetRule: '长期复利持有', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['季度财报与价格计算完全封板后次日调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'Fama-French', '规模因子', '多因子'],
    version: '2.0.0'
  },

  // 3. Carhart 4-Factor Momentum Cross-Alpha
  {
    id: 'carhart_four_factor',
    slug: 'carhart-four-factor-alpha',
    name: 'Carhart Four-Factor Momentum Cross-Alpha',
    nameZh: 'Carhart 四因子跨截面稳健动量',
    nameEn: 'Carhart Four-Factor Momentum Cross-Alpha',
    shortName: 'Carhart四因子',
    mode: 'POSITION',
    holdingPeriod: '1-6 Months',
    holdingPeriodLabel: '中期 1-6月',
    strategyFamily: 'Multi-Factor',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '1-6 Months',
    direction: 'LONG',
    author: 'Mark M. Carhart',
    origin: 'The Journal of Finance (1997)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_carhart_1997'],
    sourceReference: 'Carhart, Mark M. On Persistence in Mutual Fund Performance. The Journal of Finance 52.1 (1997): 57-82.',
    thesis: '市场 Beta、市值规模 (SMB)、账面市值比 (HML) 与 1 年期动量 (WML) 构成的四因子定价基准，能够解释绝大多数主动基金超额收益。构造同时暴露于四因子正向维度的组合具备持久 Alpha。',
    description: '华尔街资产管理公认的多因子定价与归因基石模型。',
    requiredData: ['DAILY_OHLCV', 'FINANCIALS', 'SMB_HML_MOM'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高距离(%)', type: 'number', default: -12, min: -20, max: -3, step: 1, description: '动能强度' }],
    rules: {
      type: 'group',
      id: 'carhart_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'car_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '多因子高景气度 (距高点 < 12%)' },
        { type: 'leaf', id: 'car_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '趋势发散阳线 (> 0.3%)' },
        { type: 'leaf', id: 'car_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.05, label: '机构配置换手 (RVOL >= 1.05x)' }
      ]
    },
    entry: ['四因子打分位于全截面前 15%', '技术面处于 50 与 200 日均线上方'],
    confirmation: ['月度初执行'],
    exit: ['因子综合评分降至 40% 分位以下调出'],
    rebalance: ['按月度或季度再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '固定 6.0% 止损', profitTargetRule: '长期复利', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 126 },
    antiLookaheadRules: ['次月首日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Carhart (1997) JF',
      empiricalFindings: 'Proved the 4-factor model eliminates 95% of mutual fund performance persistence, establishing the decisive role of cross-sectional momentum.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['中长线', '学术A+', 'Carhart', '四因子', '多因子'],
    version: '2.0.0'
  },

  // 4. Fama-French Value Factor (HML)
  {
    id: 'fama_french_value',
    slug: 'fama-french-book-to-market-value',
    name: 'Fama-French Book-to-Market Value Factor',
    nameZh: '经典账面市值比价值因子',
    nameEn: 'Fama-French Book-to-Market Value Factor',
    shortName: 'FF经典价值',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Value',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Eugene Fama & Kenneth French',
    origin: 'The Journal of Finance (1992)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_fama_french_1992'],
    sourceReference: 'Fama, Eugene F., and Kenneth R. French. The Cross-Section of Expected Stock Returns. The Journal of Finance 47.2 (1992): 427-465.',
    thesis: '高账面市值比 (High B/M) 代表股价相对企业净资产存在深度折价。在均值回归机制与安全边际保障下，长期持有一篮子低估值股票可斩获超额溢价。',
    description: 'Fama-French 1992 诺贝尔奖级经典价值模型（High Minus Low）。',
    requiredData: ['DAILY_OHLCV', 'BOOK_TO_MARKET', 'BALANCE_SHEET'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'peFilter', name: 'PE估值安全边际', type: 'number', default: 20, min: 8, max: 35, step: 1, description: 'PE上限' }],
    rules: {
      type: 'group',
      id: 'ff_val_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ffv_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -25, label: '排除破产崩盘股 (距高点 < 25%)' },
        { type: 'leaf', id: 'ffv_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '低估值底企稳 (> 0.1%)' },
        { type: 'leaf', id: 'ffv_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '稳定基本面流动性' }
      ]
    },
    entry: ['B/M 位于行业前 30%', '未发生破产资不抵债', '月线企稳'],
    confirmation: ['半年度调仓'],
    exit: ['估值修复至行业中位数以上退出'],
    rebalance: ['半年度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 宽幅风控止损', profitTargetRule: '估值均值修复至中枢', invalidationThreshold: '基本面发生实质破损', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['财报公告后次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Fama & French (1992) JF',
      empiricalFindings: 'Demonstrated average monthly return spread of 0.40% between high B/M and low B/M stocks over 1963-1990.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '价值因子', 'Fama-French', '安全边际'],
    version: '2.0.0'
  },

  // 5. Fama-French Robust Profitability (RMW)
  {
    id: 'fama_french_profitability',
    slug: 'fama-french-robust-profitability',
    name: 'Fama-French Robust Profitability Factor',
    nameZh: '稳健营业利润率因子',
    nameEn: 'Fama-French Robust Profitability Factor (RMW)',
    shortName: 'FF高盈利因子',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Profitability',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Eugene Fama & Kenneth French',
    origin: 'Journal of Financial Economics (2015)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_fama_french_2015'],
    sourceReference: 'Fama, Eugene F., and Kenneth R. French. A Five-Factor Asset Pricing Model. JFE 116.1 (2015): 1-22.',
    thesis: '在 Fama-French 五因子模型中，营业利润率（Operating Profitability）极高的公司（Robust Minus Weak）无论在牛市还是熊市均展现出极强的持续资本回报率与超额 Alpha。',
    description: '高营业利润率核心盈利能力因子组合。',
    requiredData: ['DAILY_OHLCV', 'OPERATING_PROFITABILITY', 'FINANCIALS'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距高点距离(%)', type: 'number', default: -15, min: -25, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'ff_prof_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ffp_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '盈利优质标的运行平稳 (距高点 < 15%)' },
        { type: 'leaf', id: 'ffp_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '温和上涨走势 (> 0.2%)' },
        { type: 'leaf', id: 'ffp_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '机构配置流动性' }
      ]
    },
    entry: ['营业利润率位于全市场前 20%', '运行在 200 日均线上方'],
    confirmation: ['季度调仓'],
    exit: ['盈利能力出现连续两季度恶化'],
    rebalance: ['按季度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.0% 跟踪止损', profitTargetRule: '复利滚动持有', invalidationThreshold: '净利润转负', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['财报审计完全披露后次日执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '盈利因子', '五因子', '高质量'],
    version: '2.0.0'
  },

  // 6. Fama-French Conservative Investment (CMA)
  {
    id: 'fama_french_investment',
    slug: 'fama-french-conservative-investment',
    name: 'Fama-French Conservative Investment Factor',
    nameZh: '保守资产投资扩张因子',
    nameEn: 'Fama-French Conservative Investment Factor (CMA)',
    shortName: 'FF保守投资因子',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Investment',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Eugene Fama & Kenneth French',
    origin: 'Journal of Financial Economics (2015)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_fama_french_2015'],
    sourceReference: 'Fama, Eugene F., and Kenneth R. French. JFE (2015).',
    thesis: '资产扩张速度过快（激进盲目资本支出与扩张并购）的企业往往稀释股东回报并带来运营低效；而保守谨慎资本支出（Conservative Minus Aggressive）的企业未来 ROIC 与股票回报显著占优。',
    description: '稳健资产投资扩张率（低资产增速、高自由现金流）策略。',
    requiredData: ['DAILY_OHLCV', 'ASSET_GROWTH_RATE'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -18, min: -25, max: -5, step: 1, description: '价格位置' }],
    rules: {
      type: 'group',
      id: 'ff_inv_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ffi_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '形态稳健 (距高点 < 18%)' },
        { type: 'leaf', id: 'ffi_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '收红稳固 (> 0.1%)' },
        { type: 'leaf', id: 'ffi_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '充沛流动性' }
      ]
    },
    entry: ['总资产年增速低于行业中位数', '自由现金流为正', '处于多头通道'],
    confirmation: ['半年度调整'],
    exit: ['出现激进资本支出或大规模高溢价并购'],
    rebalance: ['按半年再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 宽幅止损', profitTargetRule: '长期复利持有', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['财报审计完全披露后执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '投资因子', '五因子', '自由现金流'],
    version: '2.0.0'
  },

  // 7. Robert Novy-Marx Gross Profitability Factor
  {
    id: 'novy_marx_profitability',
    slug: 'novy-marx-gross-profitability-premium',
    name: 'Robert Novy-Marx Gross Profitability Premium',
    nameZh: 'Novy-Marx 资产毛利率因子',
    nameEn: 'Robert Novy-Marx Gross Profitability Premium',
    shortName: 'Novy-Marx毛利溢价',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Gross Profitability',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Robert Novy-Marx',
    origin: 'Journal of Financial Economics (2013)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_novy_marx_2013'],
    sourceReference: 'Novy-Marx, Robert. The Other Side of Value: The Gross Profitability Premium. JFE 108.1 (2013): 1-28.',
    thesis: '毛利润除以总资产（Gross Profitability）是最纯粹衡量企业真实生产力与护城河的指标，不受研发与会计折旧操控，且与价值因子负相关，具有绝佳收益增强与防守能力。',
    description: '学术界最负盛名的高毛利质地溢价模型。',
    requiredData: ['DAILY_OHLCV', 'GROSS_PROFIT_TO_ASSETS'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高距离(%)', type: 'number', default: -12, min: -20, max: -4, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'novy_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'nm_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '护城河高企标的高位运行 (距高点 < 12%)' },
        { type: 'leaf', id: 'nm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '多头长阳走强 (> 0.3%)' },
        { type: 'leaf', id: 'nm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.05, label: '机构配置流动性' }
      ]
    },
    entry: ['毛利润/总资产比率位于行业前 20%', '股价运行在 200 日均线上方'],
    confirmation: ['半年度再平衡'],
    exit: ['毛利率大幅滑坡跌出前 40% 分位'],
    rebalance: ['半年度等权'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '长期复利', invalidationThreshold: '毛利率崩塌', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Novy-Marx (2013) JFE',
      empiricalFindings: 'Demonstrated gross profitability strategies have higher Sharpe ratio than standard book-to-market value strategies.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'Novy-Marx', '毛利率', '优质资产'],
    version: '2.0.0'
  },

  // 8. Hou-Xue-Zhang Q-Factor Investment & ROE Composite
  {
    id: 'q_factor_growth_combo',
    slug: 'hou-xue-zhang-q-factor-composite',
    name: 'Hou-Xue-Zhang Q-Factor Investment & ROE Composite',
    nameZh: '侯-薛-张 Q-Factor 投资ROE复合',
    nameEn: 'Hou-Xue-Zhang Q-Factor Investment & ROE Composite',
    shortName: 'Q-Factor复合',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Investment',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Kewei Hou, Chen Xue & Lu Zhang',
    origin: 'The Review of Financial Studies (2015)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_hou_xue_zhang_2015'],
    sourceReference: 'Hou, Kewei, Chen Xue, and Lu Zhang. Digesting Anomalies: An Investment Approach. RFS 28.3 (2015): 650-705.',
    thesis: '新古典经济学投资理论证明：高 ROE（高盈利能力）叠加低资本支出资产扩张率（低投资）的企业，其未来期望现金流折现回报最大。',
    description: '学术界挑战 Fama-French 的革命性 Q 因子投资与净资产收益率双优模型。',
    requiredData: ['DAILY_OHLCV', 'ROE_ROE_GROWTH', 'INVESTMENT_TO_ASSETS'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距高点距离(%)', type: 'number', default: -14, min: -22, max: -4, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'q_fact_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'qf_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -14, label: '保持在中高位 (距高点 < 14%)' },
        { type: 'leaf', id: 'qf_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '多头阳线企稳 (> 0.2%)' },
        { type: 'leaf', id: 'qf_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛流动性' }
      ]
    },
    entry: ['ROE 处于前 20%', '投资资产增长率处于低位后 30%', '处于 200 日均线上方'],
    confirmation: ['季度再平衡'],
    exit: ['ROE 大幅恶化跌破前 40% 分位'],
    rebalance: ['季度等权'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '长期复利', invalidationThreshold: 'ROE 恶化转负', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Hou, Xue, & Zhang (2015) RFS',
      empiricalFindings: 'Demonstrated the q-factor model substantially outperforms the Fama-French 3-factor and Carhart 4-factor models.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'Q-Factor', 'ROE', '低投资', '高质量'],
    version: '2.0.0'
  },

  // 9. Joseph Piotroski F-Score High Quality
  {
    id: 'piotroski_f_score',
    slug: 'piotroski-f-score-high-quality',
    name: 'Joseph Piotroski 9-Point Fundamental Quality',
    nameZh: '皮尔托斯基 9 分制质地评分',
    nameEn: 'Joseph Piotroski 9-Point Fundamental Quality',
    shortName: '皮尔托斯基F-Score',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Piotroski F-Score',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Joseph D. Piotroski',
    origin: 'Journal of Accounting Research (2000)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_piotroski_2000'],
    sourceReference: 'Piotroski, Joseph D. Value Investing: The Use of Historical Financial Statement Information. Journal of Accounting Research 38 (2000): 1-41.',
    thesis: '在 9 项严谨财务指标（盈利、杠杆、流动性、运营效率）中取得 8-9 分的高质地企业，彻底排除了价值陷阱（Value Traps），年化超额收益极高。',
    description: '斯坦福大学教授开创的 9 分制财务健康度与基本面质地长线优选模型。',
    requiredData: ['DAILY_OHLCV', 'FINANCIALS', 'PIOTROSKI_FSCORE'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [
      { id: 'minScore', name: '最低 F-Score 分数', type: 'number', default: 8, min: 7, max: 9, step: 1, description: '8分或9分极高质地' }
    ],
    rules: {
      type: 'group',
      id: 'fscore_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'fscore_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '形态稳健未深度破位 (距高点 < 18%)' },
        { type: 'leaf', id: 'fscore_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '多头温和走红 (> 0.1%)' },
        { type: 'leaf', id: 'fscore_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '流动性充沛' }
      ]
    },
    entry: ['Piotroski F-Score >= 8 分', '处于 200 日均线上方'],
    confirmation: ['财报季后调仓'],
    exit: ['F-Score 降至 6 分以下平仓'],
    rebalance: ['按年度或半年度再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 宽幅止损', profitTargetRule: '长期复利持有', invalidationThreshold: 'F-Score 评分大跌', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Piotroski (2000) JAR',
      empiricalFindings: 'Demonstrated buying high F-score (8-9) firms generated an annual excess return of 23% over buying low F-score firms.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'Piotroski', 'F-Score', '基本面质地', '财务健康'],
    version: '2.0.0'
  },

  // 10. AQR Quality Minus Junk (QMJ) Composite
  {
    id: 'asness_quality_minus_junk',
    slug: 'asness-quality-minus-junk-qmj',
    name: 'AQR Quality Minus Junk (QMJ) Composite',
    nameZh: 'AQR 优质资产做多垃圾做空',
    nameEn: 'AQR Quality Minus Junk (QMJ) Composite',
    shortName: 'AQR质量做多',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Quality',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Clifford S. Asness, Andrea Frazzini & Lasse Pedersen',
    origin: 'Review of Accounting Studies (2019)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_asness_frazzini_pedersen_2019'],
    sourceReference: 'Asness, Clifford S., Andrea Frazzini, and Lasse Heje Pedersen. Quality Minus Junk. Review of Accounting Studies 24.1 (2019): 34-112.',
    thesis: '高质量资产（高盈利能力、高增长性、高安全边际、高股东回报）在多国股票市场均提供长达几十年的显著风险调整后正 Alpha。',
    description: 'AQR 团队经典的 Quality Minus Junk 跨国实证长周期优质股票组合。',
    requiredData: ['DAILY_OHLCV', 'QMJ_SCORE'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -15, min: -22, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'qmj_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'qmj_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '优质龙头标的运行稳健 (距高点 < 15%)' },
        { type: 'leaf', id: 'qmj_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '收红走强 (> 0.2%)' },
        { type: 'leaf', id: 'qmj_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛流动性' }
      ]
    },
    entry: ['QMJ 质量打分位于全市场前 15%', '处于 200 日均线上方'],
    confirmation: ['半年度调整'],
    exit: ['质量评分跌破前 40% 分位'],
    rebalance: ['按半年等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '长期复利', invalidationThreshold: '质地降级', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Asness, Frazzini, & Pedersen (2019)',
      empiricalFindings: 'Demonstrated high-quality stocks earn high risk-adjusted returns across 24 countries, outperforming junk stocks with statistical significance.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'AQR', 'QMJ', '质量因子', '优质资产'],
    version: '2.0.0'
  },

  // 11. Baker-Wurgler Low Volatility Anomaly
  {
    id: 'low_volatility_anomaly',
    slug: 'baker-wurgler-low-volatility-anomaly',
    name: 'Baker-Wurgler Low Volatility Anomaly',
    nameZh: '贝克-沃格勒低波动率异象',
    nameEn: 'Baker-Wurgler Low Volatility Anomaly Quality Alpha',
    shortName: '低波动率异象',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Low Volatility',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Malcolm Baker, Brendan Bradley & Jeffrey Wurgler',
    origin: 'Financial Analysts Journal (2011)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_baker_bradley_wurgler_2011'],
    sourceReference: 'Baker, Malcolm, Brendan Bradley, and Jeffrey Wurgler. Benchmarks as Limits to Arbitrage: Understanding the Low-Volatility Anomaly. FAJ 67.1 (2011): 40-54.',
    thesis: '机构投资者的基准追踪限制与委托代理冲突，导致其过度追捧高贝塔标的；而历史波动率最低的五分位股票长期夏普比率与风险调整收益显著压倒高波动股票。',
    description: '长期战胜市场的低波动率异象防守型进攻配置模型。',
    requiredData: ['DAILY_OHLCV', 'VOLATILITY_252D'],
    requiredIndicators: ['atr_percent', 'changePercent', 'relative_volume'],
    parameters: [
      { id: 'maxAtr', name: '日内真实波幅上限(%)', type: 'number', default: 2.0, min: 1.0, max: 3.5, step: 0.1, description: '低波动过滤' }
    ],
    rules: {
      type: 'group',
      id: 'low_vol_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'lv_atr', indicatorId: 'atr_percent', operator: 'LTE', value: 2.0, label: '日均真实波幅处于低位 (ATR% <= 2.0%)' },
        { type: 'leaf', id: 'lv_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '温和稳健收红 (> 0.1%)' },
        { type: 'leaf', id: 'lv_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.9, label: '流动性充沛 (RVOL >= 0.9x)' }
      ]
    },
    entry: ['年化波动率处于全市场最低五分位', '基本面稳健盈利', '处于 200 日均线上方'],
    confirmation: ['季度调仓'],
    exit: ['波动率异动大增或跌破 200 日均线'],
    rebalance: ['季度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '固定 6.0% 止损', profitTargetRule: '长期稳健复利持有', invalidationThreshold: '波动率急剧翻倍', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['季度首日执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Baker et al. (2011) FAJ',
      empiricalFindings: 'Demonstrated lowest-volatility quintile portfolio outperformed highest-volatility quintile by over 400 bps annualized with 30% lower risk.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A', '低波动', '防御', '风险平价'],
    version: '2.0.0'
  },

  // 12. Frazzini-Pedersen Betting Against Beta (BAB)
  {
    id: 'betting_against_beta',
    slug: 'frazzini-pedersen-betting-against-beta',
    name: 'Frazzini-Pedersen Betting Against Beta',
    nameZh: '弗拉齐尼低 Beta 杠杆溢价',
    nameEn: 'Frazzini-Pedersen Betting Against Beta (BAB)',
    shortName: '低Beta溢价',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Low Beta',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Andrea Frazzini & Lasse Heje Pedersen',
    origin: 'Journal of Financial Economics (2014)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_frazzini_pedersen_2014'],
    sourceReference: 'Frazzini, Andrea, and Lasse Heje Pedersen. Betting Against Beta. JFE 111.1 (2014): 1-25.',
    thesis: '借贷受限的投资者通过购买高 Beta 股票获取杠杆，使得高 Beta 资产估值长期虚高；反之做多低 Beta 资产具有极高夏普比率，风险调整收益极其丰厚。',
    description: 'AQR 经典 Betting Against Beta 长线纯多头执行策略。',
    requiredData: ['DAILY_OHLCV', 'BETA_1Y'],
    requiredIndicators: ['atr_percent', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'maxBeta', name: 'Beta上限', type: 'number', default: 0.8, min: 0.4, max: 1.0, step: 0.05, description: '低Beta过滤' }],
    rules: {
      type: 'group',
      id: 'bab_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'bab_atr', indicatorId: 'atr_percent', operator: 'LTE', value: 2.2, label: '低贝塔低波幅 (ATR% <= 2.2%)' },
        { type: 'leaf', id: 'bab_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '温和收红稳健 (> 0.1%)' },
        { type: 'leaf', id: 'bab_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '流动性优良' }
      ]
    },
    entry: ['Beta 处于 0.4 - 0.8 低区间', '处于 200 日均线上方'],
    confirmation: ['半年度调整'],
    exit: ['Beta 攀升超过 1.0 或跌破 200 日均线'],
    rebalance: ['半年度等权'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '6.5% 止损', profitTargetRule: '长期复利', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Frazzini & Pedersen (2014) JFE',
      empiricalFindings: 'BAB factor generates significant positive risk-adjusted returns across 20 global equity markets.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'BAB', '低Beta', 'AQR'],
    version: '2.0.0'
  },

  // 13. Ang Low Idiosyncratic Volatility Quality
  {
    id: 'idiosyncratic_vol_discount',
    slug: 'ang-low-idiosyncratic-volatility-quality',
    name: 'Ang Low Idiosyncratic Volatility Quality',
    nameZh: '安格低特异波动优质资产',
    nameEn: 'Ang Low Idiosyncratic Volatility Quality',
    shortName: '低特异波动优质',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Low Volatility',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Andrew Ang, Robert Hodrick, Yuhang Xing & Xiaoyan Zhang',
    origin: 'The Journal of Finance (2006)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_ang_hodrick_xing_zhang_2006'],
    sourceReference: 'Ang, Andrew, et al. The Cross-Section of Volatility and Expected Returns. The Journal of Finance 61.1 (2006): 259-299.',
    thesis: '在 Fama-French 模型残差回归中，特异性波动率（Idiosyncratic Volatility）最高的一组股票未来表现极其糟糕，而低特异波动率资产拥有持续优质溢价。',
    description: '过滤高个股特异波动风险、做多低特异风险核心资产模型。',
    requiredData: ['DAILY_OHLCV', 'IDIOSYNCRATIC_VOLATILITY'],
    requiredIndicators: ['atr_percent', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'maxAtr', name: '日均波幅上限(%)', type: 'number', default: 2.2, min: 1.0, max: 3.5, step: 0.1, description: '低波幅门槛' }],
    rules: {
      type: 'group',
      id: 'ivol_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'iv_atr', indicatorId: 'atr_percent', operator: 'LTE', value: 2.2, label: '特异波幅低平稳定 (ATR% <= 2.2%)' },
        { type: 'leaf', id: 'iv_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '温和收红 (> 0.1%)' },
        { type: 'leaf', id: 'iv_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '充沛流动性' }
      ]
    },
    entry: ['特异波动率位于全市场最低 20%', '处于 200 日均线上方'],
    confirmation: ['季度调仓'],
    exit: ['特异波动率异常飙升'],
    rebalance: ['按季度等权'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '6.5% 止损', profitTargetRule: '长期复利持有', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '低特异波动', 'Ang', '优质资产'],
    version: '2.0.0'
  },

  // 14. Asness Value + Momentum Composite
  {
    id: 'value_and_momentum_everywhere',
    slug: 'asness-value-and-momentum-everywhere',
    name: 'Asness Value + Momentum Composite',
    nameZh: '价值与动量全球协同复合',
    nameEn: 'Asness Value and Momentum Composite',
    shortName: '价值动量复合',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Value + Momentum',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Clifford S. Asness, Tobias Moskowitz & Lasse Pedersen',
    origin: 'The Journal of Finance (2013)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_asness_moskowitz_pedersen_2013'],
    sourceReference: 'Asness, Clifford S., Tobias J. Moskowitz, and Lasse Heje Pedersen. Value and Momentum Everywhere. The Journal of Finance 68.3 (2013): 929-985.',
    thesis: '价值因子与动量因子天然具有强烈的负相关性（约 -0.5）。将两者 50/50 等权组合，可在保持年化超额收益的同时将组合最大回撤降低 40% 以上，实现夏普比率翻倍。',
    description: 'AQR 团队顶级期刊成果：价值与动量双轮驱动长周期配置模型。',
    requiredData: ['DAILY_OHLCV', 'BOOK_TO_MARKET', 'MOMENTUM_12M'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '动量强度边界(%)', type: 'number', default: -12, min: -20, max: -4, step: 1, description: '动量门槛' }],
    rules: {
      type: 'group',
      id: 'val_mom_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'vm_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '动量健康未破位 (距高点 < 12%)' },
        { type: 'leaf', id: 'vm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '协同上行阳线 (> 0.3%)' },
        { type: 'leaf', id: 'vm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.05, label: '机构配置换手' }
      ]
    },
    entry: ['价值排名位于前 40%', '动量排名位于前 30%', '复合得分居前 15%'],
    confirmation: ['季度调仓'],
    exit: ['复合得分跌出前 40% 分位'],
    rebalance: ['季度等权再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '双轮驱动长期复利', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月首日开盘执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Asness et al. (2013) JF',
      empiricalFindings: 'Demonstrated 50/50 value and momentum blend achieves a Sharpe ratio nearly double that of either factor alone across US equities.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '价值+动量', 'AQR', '负相关互补'],
    version: '2.0.0'
  },

  // 15. Sloan Low Accruals Cash Flow Quality
  {
    id: 'sloan_accrual_quality',
    slug: 'sloan-low-accruals-quality',
    name: 'Sloan Low Accruals Cash Flow Quality',
    nameZh: '斯隆低应计经营现金流质地',
    nameEn: 'Sloan Low Accruals Cash Flow Quality',
    shortName: '低应计现金流质地',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Accruals',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Richard G. Sloan',
    origin: 'The Accounting Review (1996)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_sloan_1996'],
    sourceReference: 'Sloan, Richard G. The Accounting Review 71.3 (1996): 289-315.',
    thesis: '净利润中非现金应收应付账款占比高（高应计）的企业盈利持久性差；反之经营现金流充沛且低应计的企业具有极高质量的盈利转化率，长期战胜基准。',
    description: '会计学经典应计异象：寻找真金白银真金流企业。',
    requiredData: ['DAILY_OHLCV', 'NET_INCOME', 'OPERATING_CASH_FLOW'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -18, min: -25, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'sloan_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'sl_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '形态稳固 (距高点 < 18%)' },
        { type: 'leaf', id: 'sl_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '温和收红 (> 0.1%)' },
        { type: 'leaf', id: 'sl_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '流动性健康' }
      ]
    },
    entry: ['经营现金流显著大于净利润', '应计占比处于最低 20%', '处于 200 日均线上方'],
    confirmation: ['年报/季报披露后调仓'],
    exit: ['经营现金流连续两季转负平仓'],
    rebalance: ['按年度或半年度再平衡'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 止损', profitTargetRule: '长期复利', invalidationThreshold: '经营现金流转负', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '应计异象', 'Sloan', '现金流质量'],
    version: '2.0.0'
  },

  // 16. Lakonishok Contrarian Extrapolation Value
  {
    id: 'lakonishok_contrarian_value',
    slug: 'lakonishok-contrarian-extrapolation-value',
    name: 'Lakonishok Contrarian Extrapolation Value',
    nameZh: '行为逆向低估值修复',
    nameEn: 'Lakonishok Contrarian Extrapolation Value',
    shortName: '行为逆向价值修复',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Value',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Josef Lakonishok, Andrei Shleifer & Robert Vishny',
    origin: 'The Journal of Finance (1994)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_lakonishok_shleifer_vishny_1994'],
    sourceReference: 'Lakonishok, Josef, Andrei Shleifer, and Robert W. Vishny. The Journal of Finance 49.5 (1994): 1541-1578.',
    thesis: '投资者过度外推过往短期衰退导致过度惩罚价值股。当负面情绪被过度计价后，一旦出现边际盈利改善，估值将迎来戴维斯双击式的报复性均值修复。',
    description: '行为金融学经典逆向价值投资模型。',
    requiredData: ['DAILY_OHLCV', 'CASH_FLOW_TO_PRICE', 'BOOK_TO_MARKET'],
    requiredIndicators: ['rsi', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'rsiBound', name: '企稳RSI阈值', type: 'number', default: 42, min: 30, max: 55, step: 1, description: '右侧企稳' }],
    rules: {
      type: 'group',
      id: 'lakon_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'lk_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 38, max: 60 }, label: '低位温和回暖 (RSI 38-60)' },
        { type: 'leaf', id: 'lk_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '反转企稳阳线 (> 0.2%)' },
        { type: 'leaf', id: 'lk_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '正常换手' }
      ]
    },
    entry: ['现金流/价格比处于前 20%', '技术面出现右侧双底抬高企稳', 'RVOL >= 1.0x'],
    confirmation: ['半年度调仓'],
    exit: ['估值乘数恢复至历史均值平仓'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 宽幅止损', profitTargetRule: '估值修复至行业均值', invalidationThreshold: '跌破长期平台', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '逆向投资', '行为金融', '估值修复'],
    version: '2.0.0'
  },

  // 17. Dividend Aristocrats & Free Cash Flow Compounding
  {
    id: 'dividend_yield_growth',
    slug: 'dividend-growth-cash-flow-compounding',
    name: 'Dividend Aristocrats & Cash Flow Compounding',
    nameZh: '稳健股息增长与现金流复利',
    nameEn: 'Dividend Aristocrats & Free Cash Flow Compounding',
    shortName: '股息增长复利',
    mode: 'POSITION',
    holdingPeriod: '3-24 Months',
    holdingPeriodLabel: '长线 3-24月',
    strategyFamily: 'Quality',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-24 Months',
    direction: 'LONG',
    author: 'David Fish / Asness, Frazzini & Pedersen',
    origin: 'Dividend Champions / Quality Minus Junk (2019)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_asness_frazzini_pedersen_2019'],
    sourceReference: 'Asness, Clifford S., et al. Review of Accounting Studies (2019).',
    thesis: '连续 10 年以上持续增加股息分配并具备充足自由现金流覆盖率的企业，拥有无法撼动的经济护城河，长期全收益复利大幅战胜标普大盘。',
    description: '高质量股息贵族与强劲自由现金流长周期复利模型。',
    requiredData: ['DAILY_OHLCV', 'DIVIDEND_GROWTH_YEARS', 'FCF_PAYOUT_RATIO'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -15, min: -25, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'div_comp_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'dc_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '护城河资产走势稳固 (距高点 < 15%)' },
        { type: 'leaf', id: 'dc_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '温和走阳 (> 0.1%)' },
        { type: 'leaf', id: 'dc_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '充沛机构持股' }
      ]
    },
    entry: ['连续 10 年以上股息正增长', '自由现金流派息比率 < 65%', '位于 200 日均线上方'],
    confirmation: ['年度调仓'],
    exit: ['企业宣布暂停或削减股息分配立即清仓'],
    rebalance: ['按年度再平衡并进行股息再投资 (DRIP)'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '削减股息即刻止损退出', profitTargetRule: '长期全收益复利滚动', invalidationThreshold: '削减股息', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['股息公告后执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A', '股息贵族', '现金流', '护城河', 'DRIP'],
    version: '2.0.0'
  },

  // 18. Mark Minervini 8-Point Trend Template (VCP)
  {
    id: 'minervini_trend_template',
    slug: 'mark-minervini-trend-template-vcp',
    name: 'Mark Minervini 8-Point Trend Template',
    nameZh: '米奈尔维尼 8 要素大趋势模板',
    nameEn: 'Mark Minervini 8-Point Trend Template',
    shortName: '米奈尔维尼大趋势',
    mode: 'POSITION',
    holdingPeriod: '1-6 Months',
    holdingPeriodLabel: '中期 1-6月',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'position',
    horizon: '1-6 Months',
    direction: 'LONG',
    author: 'Mark Minervini',
    origin: 'Trade Like a Stock Market Wizard (2013)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_minervini_2013'],
    sourceReference: 'Minervini, Mark. Trade Like a Stock Market Wizard. McGraw-Hill, 2013.',
    thesis: '锁定处于第二阶段（Stage 2）明确上升趋势的成长股。严格遵循 200/150/50 日均线多头对齐，捕捉动量扩张主升浪。',
    description: '美股交易大赛冠军 Mark Minervini 经典第二阶段趋势模板与波动收缩（VCP）模型。',
    requiredData: ['DAILY_OHLCV', 'SMA_200', 'SMA_150', 'SMA_50', 'LOW_52W', 'HIGH_52W'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [
      { id: 'distTolerance', name: '距52周新高容忍(%)', type: 'number', default: -15, min: -25, max: -5, step: 1, description: '距高点距离' }
    ],
    rules: {
      type: 'group',
      id: 'minervini_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'min_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '距52周新高在15%以内' },
        { type: 'leaf', id: 'min_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '第二阶段大阳线发散 (> 0.3%)' },
        { type: 'leaf', id: 'min_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '放量主升浪确认 (RVOL >= 1.1x)' }
      ]
    },
    entry: ['股价 > SMA50 > SMA150 > SMA200', 'SMA200 趋势向上至少 1 个月', '较 52 周低点上涨至少 30%', '距 52 周新高在 15% 以内'],
    confirmation: ['突破 VCP 波动收缩枢纽点（Pivot Point）次日买入'],
    exit: ['收盘跌破 50 日均线且无法回抽平仓'],
    rebalance: ['按 1% 账户净值风险配置'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '枢纽点下方 4.0% - 6.0% 严格止损', profitTargetRule: '跟踪 50 日均线让利润完全奔跑', invalidationThreshold: '跌破 50 日均线', maxHoldingPeriodBars: 126 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['中长线', 'Minervini', '趋势模板', 'Stage 2', 'VCP', '超级成长股'],
    version: '2.0.0'
  },

  // 19. Stan Weinstein Stage 2 Institutional Markup
  {
    id: 'weinstein_stage2',
    slug: 'stan-weinstein-stage-2-markup',
    name: 'Stan Weinstein Stage 2 Institutional Markup',
    nameZh: '斯坦温斯坦第二阶段主升浪',
    nameEn: 'Stan Weinstein Stage 2 Institutional Markup',
    shortName: '温斯坦第二阶段',
    mode: 'POSITION',
    holdingPeriod: '1-6 Months',
    holdingPeriodLabel: '中期 1-6月',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'position',
    horizon: '1-6 Months',
    direction: 'LONG',
    author: 'Stan Weinstein',
    origin: 'Secrets For Profiting in Bull and Bear Markets (1988)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_weinstein_1988'],
    sourceReference: 'Weinstein, Stan. Stan Weinstein Secrets For Profiting in Bull and Bear Markets. Dow Jones-Irwin, 1988.',
    thesis: '股票生命周期分为四个阶段：筑底、主升、做头、下跌。当价格以巨量突破 30 周（150 日）平坦移动平均线上沿时，标志着第二阶段（主升浪）正式启动。',
    description: '经典阶段分析理论（Stage Analysis）之第二阶段主升浪长周期持仓策略。',
    requiredData: ['DAILY_OHLCV', 'SMA_150_WEEKLY_30'],
    requiredIndicators: ['distFrom52wHigh', 'relative_volume', 'changePercent'],
    parameters: [
      { id: 'minRvol', name: '突破周放量倍数', type: 'number', default: 1.5, min: 1.2, max: 3.5, step: 0.1, description: '放量突破确认' }
    ],
    rules: {
      type: 'group',
      id: 'weinstein_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ws_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '脱离底部突破新高 (距高点 < 15%)' },
        { type: 'leaf', id: 'ws_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.5, label: '机构巨量标志 (RVOL >= 1.5x)' },
        { type: 'leaf', id: 'ws_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.8, label: '放量大实体突破阳线 (> 0.8%)' }
      ]
    },
    entry: ['价格放量突破 30 周均线与第一阶段大底', 'RVOL >= 1.5x', '均线抬头向上'],
    confirmation: ['次周开盘买入'],
    exit: ['收盘有效跌破 30 周均线平仓'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以 30 周均线下沿为止损线 (约 5%-7%)', profitTargetRule: '完整持仓至第二阶段终结', invalidationThreshold: '跌破 30 周均线', maxHoldingPeriodBars: 126 },
    antiLookaheadRules: ['周末周K线收盘确认，下周一开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['中长线', '温斯坦', '阶段分析', 'Stage 2', '30周均线', '主升浪'],
    version: '2.0.0'
  },

  // 20. Moskowitz 12-Month Time Series Momentum
  {
    id: 'time_series_macro_momentum',
    slug: 'moskowitz-12m-time-series-momentum',
    name: 'Moskowitz 12-Month Time Series Momentum',
    nameZh: '12 个月时间序列趋势大单边',
    nameEn: 'Moskowitz 12-Month Time Series Momentum',
    shortName: '12M时间序列动量',
    mode: 'POSITION',
    holdingPeriod: '1-12 Months',
    holdingPeriodLabel: '长线 1-12月',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Academic Factor',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'position',
    horizon: '1-12 Months',
    direction: 'LONG',
    author: 'Tobias J. Moskowitz, Yao Hua Ooi & Lasse H. Pedersen',
    origin: 'Journal of Financial Economics (2012)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_moskowitz_ooi_pedersen_2012'],
    sourceReference: 'Moskowitz, Tobias J., Yao Hua Ooi, and Lasse Heje Pedersen. Time Series Momentum. JFE 104.2 (2012): 228-250.',
    thesis: '时间序列绝对动量（自身过去 12 个月总收益为正）跨资产有效。做多过去 1 年自身正回报的资产并按照波动率倒数加权，具有极佳单边趋势捕获能力。',
    description: 'JFE 顶级金融文献绝对时间序列动量趋势系统。',
    requiredData: ['DAILY_OHLCV', 'RETURN_12M_SIGN'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距高点距离(%)', type: 'number', default: -15, min: -25, max: -5, step: 1, description: '趋势稳健度' }],
    rules: {
      type: 'group',
      id: 'ts_mom_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'tsm_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '保持在多头趋势高位 (距高点 < 15%)' },
        { type: 'leaf', id: 'tsm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '稳步走阳 (> 0.2%)' },
        { type: 'leaf', id: 'tsm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛流动性' }
      ]
    },
    entry: ['过去 12 个月绝对收益率为正', '股价位于 200 日均线上方'],
    confirmation: ['月末执行调仓'],
    exit: ['12 个月累计收益转负平仓'],
    rebalance: ['按波动率倒数或等权月末再平衡'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '跌破 200 日均线平仓', profitTargetRule: '让单边趋势充分奔跑', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月首日开盘执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Moskowitz et al. (2012) JFE',
      empiricalFindings: 'Demonstrated strong positive 1-year auto-correlation generating substantial alpha across 58 liquid global markets.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', '时间序列动量', '趋势跟踪', '大单边'],
    version: '2.0.0'
  },

  // 21. Yield Sensitive High-Moat Defensive Anchor
  {
    id: 'treasury_sensitive_defense',
    slug: 'yield-sensitive-defensive-anchor',
    name: 'Yield-Sensitive High-Moat Defensive Anchor',
    nameZh: '宏观利率敏感高护城河防守锚',
    nameEn: 'Yield-Sensitive High-Moat Defensive Anchor',
    shortName: '利率敏感防守锚',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Low Volatility',
    strategySchool: 'Academic Factor',
    category: 'MACRO_REGIME',
    categoryLabel: '宏观模型 (Macro Regime)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Malcolm Baker, Brendan Bradley & Jeffrey Wurgler',
    origin: 'Financial Analysts Journal (2011)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_baker_bradley_wurgler_2011'],
    sourceReference: 'Baker, Malcolm, et al. Financial Analysts Journal (2011).',
    thesis: '在宏观利率见顶或经济下行周期中，具有稳定类债券现金流、高股息收益率和刚性消费需求的公用事业与必选消费龙头，充当组合的抗震压舱石。',
    description: '宏观防御型低波动高股息压舱石资产配置模型。',
    requiredData: ['DAILY_OHLCV', 'DIVIDEND_YIELD', 'SECTOR_DEFENSIVE'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -12, min: -20, max: -4, step: 1, description: '抗跌门槛' }],
    rules: {
      type: 'group',
      id: 'ts_def_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'td_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '极度抗跌资产 (距高点 < 12%)' },
        { type: 'leaf', id: 'td_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '平稳收红 (> 0.1%)' },
        { type: 'leaf', id: 'td_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 0.95, label: '主流大资产标的' }
      ]
    },
    entry: ['属于防守性公用事业/医疗/必选消费龙头', '股息率 > 3.0%', '距新高 < 12%'],
    confirmation: ['半年度调仓'],
    exit: ['宏观环境进入高通胀激进加息周期或跌破 200 日均线'],
    rebalance: ['按半年度再平衡'],
    riskModel: { maxRiskPerTradePercent: 1.5, stopLossRule: '6.0% 止损', profitTargetRule: '长期分红复利持有', invalidationThreshold: '跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A', '防守锚', '高股息', '低波动', '宏观抗跌'],
    version: '2.0.0'
  },

  // 22. Shareholder Yield Buyback & Dividend Compound
  {
    id: 'shareholder_yield_compound',
    slug: 'shareholder-yield-buyback-dividend-compound',
    name: 'Shareholder Yield Buyback & Dividend Compound',
    nameZh: '股东总收益与股票回购复合',
    nameEn: 'Shareholder Yield Buyback & Dividend Compound',
    shortName: '股东收益回购复合',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Quality',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Clifford S. Asness et al. / Meb Faber',
    origin: 'Shareholder Yield: A Better Approach to Dividend Investing (2013)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_asness_frazzini_pedersen_2019'],
    sourceReference: 'Faber, Mebane. Shareholder Yield: A Better Approach to Dividend Investing. The Idea Farm, 2013.',
    thesis: '单纯看股息率会忽略税收惩罚与回购。将现金股息收益率 + 净股票回购收益率 + 净偿债率汇总为“股东总收益率（Shareholder Yield）”，是学术界与机构实证预测长期超额回报的核心价值指标。',
    description: '聚焦巨额股票回购与高现金流回报公司的长周期价值复利策略。',
    requiredData: ['DAILY_OHLCV', 'SHAREHOLDER_YIELD_RATIO'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距高点距离(%)', type: 'number', default: -15, min: -22, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'sh_yld_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'sy_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '保持在健康区间 (距高点 < 15%)' },
        { type: 'leaf', id: 'sy_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '走红稳定 (> 0.2%)' },
        { type: 'leaf', id: 'sy_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛流动性' }
      ]
    },
    entry: ['股东总收益率 (股息+净回购) 位于全市场前 15%', '处于 200 日均线上方'],
    confirmation: ['半年度再平衡'],
    exit: ['回购计划中止且股东收益率跌出前 40% 分位'],
    rebalance: ['半年度等权'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '长期复利', invalidationThreshold: '增发股票稀释股东', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A', '股东总收益', '股票回购', '现金流回报'],
    version: '2.0.0'
  },

  // 23. De Bondt & Thaler 3-Year Long Term Reversal
  {
    id: 'long_term_reversal_contrarian',
    slug: 'de-bondt-thaler-3y-long-term-reversal',
    name: 'De Bondt & Thaler 3-Year Long Term Reversal',
    nameZh: '德邦特-泰勒 3 年长期逆向反转',
    nameEn: 'De Bondt & Thaler 3-Year Long Term Reversal',
    shortName: '3年长期逆向反转',
    mode: 'POSITION',
    holdingPeriod: '6-12 Months',
    holdingPeriodLabel: '长线 6-12月',
    strategyFamily: 'Value',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '6-12 Months',
    direction: 'LONG',
    author: 'Werner F. M. De Bondt & Richard Thaler',
    origin: 'The Journal of Finance (1985)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_lakonishok_shleifer_vishny_1994'],
    sourceReference: 'De Bondt, Werner F. M., and Richard Thaler. Does the Stock Market Overreact? The Journal of Finance 40.3 (1985): 793-805.',
    thesis: '行为金融学奠基论文证实：市场对长期坏消息极度过度反应。过去 3 年表现最差的极端输家组合，在未来 3-5 年显著跑赢市场 25% 以上。',
    description: '诺贝尔奖得主 Richard Thaler 行为金融学经典 3 年长期极度输家大周期均值回归策略。',
    requiredData: ['DAILY_OHLCV', 'PAST_3Y_RETURN', 'BOOK_TO_MARKET'],
    requiredIndicators: ['rsi', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'rsiBound', name: '右侧企稳RSI', type: 'number', default: 45, min: 35, max: 60, step: 1, description: '右侧走平' }],
    rules: {
      type: 'group',
      id: 'debondt_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'db_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 40, max: 62 }, label: '低位筑底完成企稳 (RSI 40-62)' },
        { type: 'leaf', id: 'db_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '反转启动小阳 (> 0.2%)' },
        { type: 'leaf', id: 'db_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '流动性承接' }
      ]
    },
    entry: ['过去 3 年累计收益位于全市场最低 10%', '未破产且经营现金流转正', '右侧突破 200 日均线'],
    confirmation: ['年度调整'],
    exit: ['长期估值与股价完成彻底均值修复平仓'],
    rebalance: ['年度等权'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '8.0% 宽幅止损', profitTargetRule: '长期大周期反转修复', invalidationThreshold: '再创新低', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'De Bondt & Thaler (1985) JF',
      empiricalFindings: 'Demonstrated 3-year prior loser portfolios outperformed 3-year prior winner portfolios by 25% over subsequent 3 years.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A+', 'Thaler', '行为金融', '长期反转', '超额修复'],
    version: '2.0.0'
  },

  // 24. Greenblatt ROC & Earnings Yield Magic Formula
  {
    id: 'magic_formula_quality_value',
    slug: 'greenblatt-magic-formula-roc-ey',
    name: 'Joel Greenblatt Magic Formula Quality & Value',
    nameZh: '格林布拉特神奇公式优质低估',
    nameEn: 'Joel Greenblatt Magic Formula Quality and Value',
    shortName: '格林布拉特神奇公式',
    mode: 'POSITION',
    holdingPeriod: '3-12 Months',
    holdingPeriodLabel: '长线 3-12月',
    strategyFamily: 'Quality',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'position',
    horizon: '3-12 Months',
    direction: 'LONG',
    author: 'Joel Greenblatt / Robert Novy-Marx',
    origin: 'The Little Book That Beats the Market (2005)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'A',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_novy_marx_2013'],
    sourceReference: 'Greenblatt, Joel. The Little Book That Beats the Market. John Wiley & Sons, 2005.',
    thesis: '买入好公司（高资本回报率 ROC = EBIT / (净流动资产 + 净固定资产)）同时买得便宜（高盈利收益率 Earnings Yield = EBIT / 企业价值 EV），两个因子综合排名第一梯队的企业长期显著战胜市场。',
    description: '哥伦比亚大学客座教授 Joel Greenblatt 经典神奇公式优质低估长线策略。',
    requiredData: ['DAILY_OHLCV', 'ROC_ROIC', 'EARNINGS_YIELD'],
    requiredIndicators: ['distFrom52wHigh', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'distTolerance', name: '距新高容忍', type: 'number', default: -16, min: -25, max: -5, step: 1, description: '稳健度' }],
    rules: {
      type: 'group',
      id: 'magic_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'mf_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -16, label: '形态稳健 (距高点 < 16%)' },
        { type: 'leaf', id: 'mf_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '温和收红企稳 (> 0.2%)' },
        { type: 'leaf', id: 'mf_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛流动性' }
      ]
    },
    entry: ['ROC 排名与 Earnings Yield 排名综合位列全市场前 10%', '市值 > 10 亿美元', '处于 200 日均线上方'],
    confirmation: ['年度调仓'],
    exit: ['神奇公式综合排名跌出前 30% 分位'],
    rebalance: ['每年按规则调仓一次'],
    riskModel: { maxRiskPerTradePercent: 2.0, stopLossRule: '7.5% 止损', profitTargetRule: '每年重新排名调仓复利', invalidationThreshold: '基本面恶化跌破 200 日均线', maxHoldingPeriodBars: 252 },
    antiLookaheadRules: ['次月调仓'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 756, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Greenblatt (2005) & Novy-Marx (2013)',
      empiricalFindings: 'Demonstrated 20-30 stock Magic Formula portfolios achieved an annualized return of over 20% on US equities from 1988 to 2004.'
    },
    defaultTimeframes: ['1D', '1W'],
    tags: ['长线', '学术A', '神奇公式', 'Greenblatt', 'ROC', '盈利收益率'],
    version: '2.0.0'
  }
];
