import { StrategyDefinition } from '../../../types.ts';

/**
 * STRATEGY LIBRARY V2.0 - SWING STRATEGIES (波段模型)
 * Target Holding Period: 5 - 20 Trading Days (1 - 4 Weeks)
 * Evidence Base: Classical trend filters, volatility channel expansions, multi-week momentum rotation, and cointegration.
 * Count: Exactly 24 models.
 */

export const SWING_MODELS: StrategyDefinition[] = [
  // 1. Donchian 20-Day Standard
  {
    id: 'donchian_breakout',
    slug: 'donchian-channel-20-day-breakout',
    name: 'Donchian Channel 20-Day Standard Breakout',
    nameZh: '唐奇安通道 20 日经典突破',
    nameEn: 'Donchian Channel 20-Day Standard Breakout',
    shortName: '唐奇安20日突破',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Richard Donchian',
    origin: 'Financial Analysts Journal (1960)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_donchian_1960'],
    sourceReference: 'Donchian, Richard. High Finance in Copper. Financial Analysts Journal 16.6 (1960): 133-142.',
    thesis: '20 个交易日（约 1 个日历月）的高点突破是趋势跟踪学派最具实证意义的基准通道。配合成交量放大，能够有效过滤盘整杂波并捕捉多周主升浪。',
    description: '趋势跟踪学派鼻祖策略。收盘价突破过去 20 周期最高点通道上轨，配合成交量放大确立波段动能。',
    requiredData: ['DAILY_OHLCV', 'DONCHIAN_20'],
    requiredIndicators: ['distFrom52wHigh', 'relative_volume', 'changePercent'],
    parameters: [
      { id: 'lookback', name: '突破周期 (天)', type: 'number', default: 20, min: 10, max: 60, step: 5, description: '经典参数为20天' },
      { id: 'minRvol', name: '放量门槛 (RVOL)', type: 'number', default: 1.2, min: 1.0, max: 3.0, step: 0.1, description: '过滤缩量假突破' }
    ],
    rules: {
      type: 'group',
      id: 'donchian_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'donchian_high_leaf', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '靠近高位区域 (距高点 < 15%)' },
        { type: 'leaf', id: 'donchian_rvol_leaf', indicatorId: 'relative_volume', operator: 'GTE', value: 1.2, label: '成交量放大 (RVOL >= 1.2x)' },
        { type: 'leaf', id: 'donchian_chg_leaf', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '当日收盘为正 (Change% > 0.2%)' }
      ]
    },
    entry: ['收盘价创 20 日新高', '成交量 RVOL >= 1.2x', '日线收阳'],
    confirmation: ['次日开盘买入'],
    exit: ['收盘跌破 10 日最低价通道下轨平仓', '或触及移动止损'],
    rebalance: ['按 1% 账户净值风险核算持仓股数'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '跌破入场日前 10 日最低价或固定 4.5% 硬止损', profitTargetRule: '追踪跌破 10 日通道下轨离场，让波段利润充分奔跑', invalidationThreshold: '跌回 20 日通道中轴', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['严格基于昨日收盘价计算，次日开盘按市价执行'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '趋势跟踪', '通道突破', '唐奇安', '经典量化'],
    version: '2.0.0'
  },

  // 2. Turtle System 1
  {
    id: 'turtle_system_1',
    slug: 'turtle-trading-system-one',
    name: 'Turtle Trading System One (20-Day Breakout)',
    nameZh: '海龟交易法则 20 日波段系统',
    nameEn: 'Turtle Trading System One Breakout',
    shortName: '海龟20日系统',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Richard Dennis & William Eckhardt',
    origin: 'Way of the Turtle (Curtis Faith, 2007)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_faith_2007'],
    sourceReference: 'Faith, Curtis. Way of the Turtle. McGraw-Hill, 2007.',
    thesis: '华尔街传奇海龟实验短期系统。突破 20 日高点建立底仓，严格基于真实波幅 N (ATR) 计算头寸大小并按 2ATR 止损。',
    description: '海龟短期经典突破系统，包含标准 2N 止损与 10 日低点离场机制。',
    requiredData: ['DAILY_OHLCV', 'ATR_20'],
    requiredIndicators: ['price', 'relative_volume', 'changePercent'],
    parameters: [
      { id: 'breakoutPeriod', name: '突破周期 (天)', type: 'number', default: 20, min: 10, max: 40, step: 5, description: '突破周期' }
    ],
    rules: {
      type: 'group',
      id: 'turtle_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'turtle_price_ma', indicatorId: 'price', operator: 'GT', value: 10, label: '股价大于$10保证流动性' },
        { type: 'leaf', id: 'turtle_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '放量启动 (RVOL >= 1.1x)' },
        { type: 'leaf', id: 'turtle_trend', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '收盘实体走强 (> 0.5%)' }
      ]
    },
    entry: ['价格突破 20 日高点', 'RVOL >= 1.1x', '实体走强'],
    confirmation: ['次日买入'],
    exit: ['跌破 10 日最低价清仓', '或触及 2ATR 止损'],
    rebalance: ['每上涨 0.5ATR 可加仓 1 单元，上限 4 单元'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '入场价下方 2ATR 严格硬止损', profitTargetRule: '跌破 10 日低点平仓', invalidationThreshold: '跌破 2ATR', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '海龟法则', 'ATR仓位', '趋势跟踪', '头寸管理'],
    version: '2.0.0'
  },

  // 3. SuperTrend Dynamic Trend Following
  {
    id: 'supertrend_momentum',
    slug: 'supertrend-dynamic-trend-following',
    name: 'SuperTrend Dynamic Momentum Following',
    nameZh: 'SuperTrend 真实波幅波段跟踪',
    nameEn: 'SuperTrend Dynamic Momentum Following',
    shortName: 'SuperTrend跟踪',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Olivier Seban',
    origin: 'New Concepts in Technical Trading Systems (ATR Trailing Method)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_wilder_1978'],
    sourceReference: 'Seban, Olivier. Tout le monde peut réussir à la bourse. Maxima, 2007.',
    thesis: 'SuperTrend 结合了中位价与真实波幅乘数，当价格站稳在 SuperTrend 动态支撑带上方时，过滤了日内噪音，精准锁定波段主升浪。',
    description: '量化界广泛使用的波段趋势跟踪利器。',
    requiredData: ['DAILY_OHLCV', 'ATR_10'],
    requiredIndicators: ['changePercent', 'relative_volume', 'rsi'],
    parameters: [
      { id: 'atrMultiplier', name: 'ATR 倍数乘数', type: 'number', default: 3.0, min: 1.5, max: 4.5, step: 0.5, description: '波幅倍数' }
    ],
    rules: {
      type: 'group',
      id: 'supertrend_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'st_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '多头信号阳线 (> 0.5%)' },
        { type: 'leaf', id: 'st_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '放量支持 (RVOL >= 1.1x)' },
        { type: 'leaf', id: 'st_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 52, max: 70 }, label: '动能健康 (RSI 52-70)' }
      ]
    },
    entry: ['价格收在 SuperTrend 支撑带上方', 'RVOL >= 1.1x', 'RSI 处于多头区间'],
    confirmation: ['次日买入'],
    exit: ['收盘价跌破 SuperTrend 翻绿平仓'],
    rebalance: ['单笔 1% 净值风险'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以 SuperTrend 动态线作为移动止损', profitTargetRule: '跟踪止盈直到击穿支撑带', invalidationThreshold: '跌破 SuperTrend 轨道', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'SuperTrend', '趋势跟踪', 'ATR', '移动止损'],
    version: '2.0.0'
  },

  // 4. Kaufman Adaptive Moving Average (KAMA)
  {
    id: 'kama_adaptive_trend',
    slug: 'kaufman-adaptive-moving-average-trend',
    name: 'Kaufman Adaptive Moving Average Dynamic Trend',
    nameZh: '考夫曼自适应均线趋势',
    nameEn: 'Kaufman Adaptive Moving Average Dynamic Trend',
    shortName: 'KAMA自适应均线',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Perry J. Kaufman',
    origin: 'Trading Systems and Methods (1998)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_kaufman_1998'],
    sourceReference: 'Kaufman, Perry J. Trading Systems and Methods. John Wiley & Sons, 1998.',
    thesis: 'KAMA 通过效率比率 (Efficiency Ratio) 动态衡量市场噪音。噪音高时均线变平钝化，趋势明确时均线敏捷贴紧价格，极大减少虚假震荡磨损。',
    description: 'Perry Kaufman 经典降噪自适应趋势跟踪模型。',
    requiredData: ['DAILY_OHLCV', 'KAMA_10_2_30'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [
      { id: 'erPeriod', name: '效率比率周期', type: 'number', default: 10, min: 5, max: 20, step: 1, description: 'ER 回看周期' }
    ],
    rules: {
      type: 'group',
      id: 'kama_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'kama_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '趋势向上通道 (距高点 < 18%)' },
        { type: 'leaf', id: 'kama_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.4, label: '均线上方发散阳线 (> 0.4%)' },
        { type: 'leaf', id: 'kama_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '成交量配合 (RVOL >= 1.1x)' }
      ]
    },
    entry: ['股价站上 KAMA 且 KAMA 斜率向上', 'RVOL >= 1.1x', '距新高不远'],
    confirmation: ['次日买入'],
    exit: ['收盘跌破 KAMA 均线平仓'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '跌破 KAMA 下方 2% 止损', profitTargetRule: '移动跟踪止盈', invalidationThreshold: '跌破 KAMA', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'KAMA', '自适应均线', '趋势跟踪', '降噪'],
    version: '2.0.0'
  },

  // 5. ADX Directional Trend Strength Filter
  {
    id: 'adx_trend_strength',
    slug: 'adx-directional-trend-strength',
    name: 'ADX Directional Trend Strength Filter',
    nameZh: 'ADX 强趋势方向动能',
    nameEn: 'ADX Directional Trend Strength Filter',
    shortName: 'ADX强趋势动能',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'J. Welles Wilder',
    origin: 'New Concepts in Technical Trading Systems (1978)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_wilder_1978'],
    sourceReference: 'Wilder, J. Welles. New Concepts in Technical Trading Systems. Trend Research, 1978.',
    thesis: 'ADX > 25 且 +DI 显著高于 -DI 代表非震荡强单边市场，在此环境下顺势突破或回踩均线具有极高波段延续度。',
    description: '平均趋向指标 (ADX) 强单边趋势过滤与波段跟进策略。',
    requiredData: ['DAILY_OHLCV', 'ADX_14', 'DMI_14'],
    requiredIndicators: ['adx', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'adxThreshold', name: 'ADX强趋势阈值', type: 'number', default: 25, min: 20, max: 40, step: 1, description: '强单边门槛' }],
    rules: {
      type: 'group',
      id: 'adx_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'adx_val', indicatorId: 'adx', operator: 'GTE', value: 25, label: '强单边趋势展开 (ADX >= 25)' },
        { type: 'leaf', id: 'adx_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '多头收红阳线 (> 0.3%)' },
        { type: 'leaf', id: 'adx_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.05, label: '正常流动性 (RVOL >= 1.05x)' }
      ]
    },
    entry: ['ADX >= 25', '+DI > -DI', '收盘走强'],
    confirmation: ['次日买入'],
    exit: ['ADX 见顶转跌且跌破 25 离场，或出现长阴线'],
    rebalance: ['固定 1% 账户净值风险'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.0% 止损', profitTargetRule: '跟踪止盈，目标 1:2 盈亏比', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'ADX', 'DMI', '强趋势', '怀尔德'],
    version: '2.0.0'
  },

  // 6. Triple EMA Alignment
  {
    id: 'triple_ema_alignment',
    slug: 'triple-ema-alignment-bullish-wave',
    name: 'Triple Exponential Moving Average Bullish Wave',
    nameZh: '三重指数平滑均线多头共振',
    nameEn: 'Triple Exponential Moving Average Bullish Wave',
    shortName: '三重大均线多头',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Patrick Mulloy',
    origin: 'Technical Analysis of Stocks & Commodities (1994)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Mulloy, Patrick. Smoothing Data with Faster Moving Averages. TASC, 1994.',
    thesis: '短期、中期、长期三条均线（如 EMA 8, 21, 55）呈现完美的多头排列与向上发散，代表全周期多头共识达成。',
    description: '多重指数平滑均线多头排列波段策略。',
    requiredData: ['DAILY_OHLCV', 'EMA_8', 'EMA_21', 'EMA_55'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [{ id: 'minChg', name: '突破实体(%)', type: 'number', default: 0.5, min: 0.2, max: 2.0, step: 0.1, description: '涨幅' }],
    rules: {
      type: 'group',
      id: 'tema_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'tema_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -15, label: '高位主升浪通道 (距高点 < 15%)' },
        { type: 'leaf', id: 'tema_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '多头排列上冲阳线 (> 0.5%)' },
        { type: 'leaf', id: 'tema_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '温和放量 (RVOL >= 1.1x)' }
      ]
    },
    entry: ['EMA(8) > EMA(21) > EMA(55)', '收盘价在所有均线上方', '放量发散'],
    confirmation: ['次日买入'],
    exit: ['收盘跌破 EMA(21) 离场'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以 EMA 21 为移动止损线 (约 3.5%-4.5%)', profitTargetRule: '跟踪止盈让利润奔跑', invalidationThreshold: '跌破 EMA 21', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'EMA', '均线多头', '趋势共振'],
    version: '2.0.0'
  },

  // 7. Nicolas Darvas Box Range Breakout
  {
    id: 'darvas_box',
    slug: 'darvas-box-range-breakout',
    name: 'Nicolas Darvas Box Range Breakout',
    nameZh: '达瓦斯箱体放量突破',
    nameEn: 'Nicolas Darvas Box Range Breakout',
    shortName: '达瓦斯箱体突破',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'BREAKOUT',
    categoryLabel: '通道突破 (Breakout)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Nicolas Darvas',
    origin: 'How I Made $2,000,000 in the Stock Market (1960)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_darvas_1960'],
    sourceReference: 'Darvas, Nicolas. How I Made $2,000,000 in the Stock Market. American Research Council, 1960.',
    thesis: '牛股上涨总是以阶梯式箱体演进。当价格在明确的高低边界内震荡巩固后，放巨量突破箱顶，预示新一阶箱体空间的开启。',
    description: 'Nicolas Darvas 传奇箱体理论波段突破模型，直接联动 K 线箱体图层渲染。',
    requiredData: ['DAILY_OHLCV', 'DARVAS_BOX'],
    requiredIndicators: ['darvas_box_breakout', 'relative_volume', 'changePercent'],
    parameters: [
      { id: 'minRvol', name: '突破放量门槛', type: 'number', default: 1.3, min: 1.0, max: 3.0, step: 0.1, description: '放量' }
    ],
    rules: {
      type: 'group',
      id: 'darvas_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'darvas_bk', indicatorId: 'darvas_box_breakout', operator: 'EQ', value: true, label: '放量突破箱顶上沿' },
        { type: 'leaf', id: 'darvas_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.3, label: '大资金放量 (RVOL >= 1.3x)' },
        { type: 'leaf', id: 'darvas_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.8, label: '坚实实体阳线 (> 0.8%)' }
      ]
    },
    entry: ['价格放量突破达瓦斯箱顶', 'RVOL >= 1.3x', '日K阳线 > 0.8%'],
    confirmation: ['次日买入'],
    exit: ['跌破原箱顶回踩线或跌回箱体内离场'],
    rebalance: ['单笔 1% 净值风险'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以箱顶下方 1.5% 为止损线 (最大 4%)', profitTargetRule: '新箱体等幅测算目标位分批止盈', invalidationThreshold: '收盘跌回箱体内部', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '达瓦斯', '箱体突破', '阶梯趋势'],
    version: '2.0.0'
  },

  // 8. Bollinger BandWidth Volatility Squeeze
  {
    id: 'bollinger_squeeze',
    slug: 'bollinger-bandwidth-volatility-squeeze',
    name: 'Bollinger BandWidth Volatility Squeeze',
    nameZh: '布林带带宽极致收敛突破',
    nameEn: 'Bollinger BandWidth Volatility Squeeze Breakout',
    shortName: '布林极窄挤压',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'BREAKOUT',
    categoryLabel: '通道突破 (Breakout)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'John Bollinger',
    origin: 'Bollinger on Bollinger Bands (2001)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_bollinger_2001'],
    sourceReference: 'Bollinger, John. Bollinger on Bollinger Bands. McGraw-Hill, 2001.',
    thesis: '波动率由静止到爆发的物理学蓄能模型。布林带宽 (BandWidth) 压缩至 6 个月新低后，价格放量跳出上轨单边展开，孕育可观波段行情。',
    description: '经典布林带宽极致收敛（The Squeeze）与上轨爆量突破模型。',
    requiredData: ['DAILY_OHLCV', 'BOLLINGER_BANDWIDTH'],
    requiredIndicators: ['relative_volume', 'rsi', 'changePercent'],
    parameters: [{ id: 'minRvol', name: '突破放量', type: 'number', default: 1.4, min: 1.1, max: 3.0, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'bb_squeeze_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'bbs_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.4, label: '放量突破驱动 (RVOL >= 1.4x)' },
        { type: 'leaf', id: 'bbs_rsi', indicatorId: 'rsi', operator: 'GT', value: 58, label: '动能强劲突破 (RSI > 58)' },
        { type: 'leaf', id: 'bbs_chg', indicatorId: 'changePercent', operator: 'GT', value: 1.2, label: '放量大阳线 (> 1.2%)' }
      ]
    },
    entry: ['布林带经历低位挤压后突破上轨', 'RVOL >= 1.4x', '阳线 > 1.2%'],
    confirmation: ['次日买入'],
    exit: ['价格重新跌破布林带 20 日中轨平仓'],
    rebalance: ['单笔 1% 净值风险'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以布林带中轨为止损 (约 4%-5%)', profitTargetRule: '沿布林上轨持续持股，跌破中轨结清', invalidationThreshold: '跌破中轨', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '布林带', '波动率挤压', 'Squeeze', '突破'],
    version: '2.0.0'
  },

  // 9. John Carter TTM Squeeze Breakout
  {
    id: 'ttm_squeeze_breakout',
    slug: 'ttm-squeeze-standard-breakout',
    name: 'TTM Volatility Squeeze Standard Breakout',
    nameZh: 'TTM Squeeze 肯特纳挤压突破',
    nameEn: 'TTM Volatility Squeeze Standard Breakout',
    shortName: 'TTM标准挤压',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'BREAKOUT',
    categoryLabel: '通道突破 (Breakout)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'John Carter',
    origin: 'Mastering the Trade (2005)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_bollinger_2001'],
    sourceReference: 'Carter, John F. Mastering the Trade. McGraw-Hill, 2005.',
    thesis: '将布林带与肯特纳通道融合。当布林带完全落入肯特纳内部时为蓄势状态；当布林带扩张跳出肯特纳且动能柱连续递增，往往爆发持续数周的单边波段。',
    description: 'John Carter 完整版 TTM Squeeze 波段爆发模型。',
    requiredData: ['DAILY_OHLCV', 'BOLLINGER_20_2', 'KELTNER_20_1_5'],
    requiredIndicators: ['rsi', 'relative_volume', 'changePercent'],
    parameters: [{ id: 'minRvol', name: '放量倍数', type: 'number', default: 1.25, min: 1.0, max: 2.5, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'ttm_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'ttm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.25, label: '放量爆发确认 (RVOL >= 1.25x)' },
        { type: 'leaf', id: 'ttm_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 54, max: 72 }, label: '动能充沛健康 (RSI 54-72)' },
        { type: 'leaf', id: 'ttm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.8, label: '释放阳线实体 (> 0.8%)' }
      ]
    },
    entry: ['TTM 挤压解除点火', 'RVOL >= 1.25x', '涨幅 > 0.8%'],
    confirmation: ['次日买入'],
    exit: ['动能柱连续 2 日减弱平仓，或持有 20 日'],
    rebalance: ['固定风险 1%'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.0% 止损', profitTargetRule: '动能柱拐头分批止盈', invalidationThreshold: '跌破均线中轴', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'TTM Squeeze', '肯特纳通道', '布林带', '突破'],
    version: '2.0.0'
  },

  // 10. 52-Week High Frontier Blue Sky Breakout
  {
    id: 'intraday_high_breakout',
    slug: '52-week-high-frontier-breakout',
    name: '52-Week High Frontier Blue Sky Breakout',
    nameZh: '52 周新高天际线突破',
    nameEn: '52-Week High Frontier Blue Sky Breakout',
    shortName: '52周新高突破',
    mode: 'SWING',
    holdingPeriod: '5-25 Trading Days',
    holdingPeriodLabel: '波段 5-25天',
    strategyFamily: 'Cross-Sectional Momentum',
    strategySchool: 'Classical Technical',
    category: 'BREAKOUT',
    categoryLabel: '通道突破 (Breakout)',
    family: 'swing',
    horizon: '5-25 Trading Days',
    direction: 'LONG',
    author: 'Thomas Bulkowski',
    origin: 'Encyclopedia of Chart Patterns (2005)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Bulkowski, Thomas. Encyclopedia of Chart Patterns. John Wiley & Sons, 2005.',
    thesis: '创 52 周新高的股票上方没有任何历史被套筹码压力（Blue Sky），市场主力与跟风盘做多阻力最小，后续具备可观波段惯性。',
    description: '欧奈尔与动量学派核心策略：选强不选弱，做多历史天际线新高标的。',
    requiredData: ['DAILY_OHLCV', 'HIGH_52W'],
    requiredIndicators: ['distFrom52wHigh', 'relative_volume', 'changePercent'],
    parameters: [
      { id: 'distTolerance', name: '距52周新高容忍(%)', type: 'number', default: -1.0, min: -3.0, max: 0.0, step: 0.5, description: '距离新高距离' }
    ],
    rules: {
      type: 'group',
      id: 'high52_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'h52_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -1.0, label: '创出或逼近52周新高 (>= -1.0%)' },
        { type: 'leaf', id: 'h52_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.3, label: '放量大资金攻顶 (RVOL >= 1.3x)' },
        { type: 'leaf', id: 'h52_chg', indicatorId: 'changePercent', operator: 'GT', value: 1.0, label: '新高大阳线 (> 1.0%)' }
      ]
    },
    entry: ['距 52 周最高价 <= 1%', 'RVOL >= 1.3x', '日线涨幅 > 1.0%'],
    confirmation: ['次日买入'],
    exit: ['跌破突破点下方 3.5% 止损，或持有 25 天退出'],
    rebalance: ['固定 1% 账户风险'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '新高突破平台下方 3.5% 止损', profitTargetRule: '移动追踪止盈', invalidationThreshold: '收盘跌破突破平台', maxHoldingPeriodBars: 25 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '52周新高', '动量', '天际线', '突破'],
    version: '2.0.0'
  },

  // 11. On-Balance Volume (OBV) Stealth Accumulation Wave
  {
    id: 'obv_institutional_accum',
    slug: 'obv-stealth-accumulation-wave',
    name: 'On-Balance Volume Stealth Accumulation Wave',
    nameZh: 'OBV 能量潮机构隐蔽建仓',
    nameEn: 'On-Balance Volume Stealth Accumulation Wave',
    shortName: 'OBV隐蔽建仓',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Microstructure & Volume',
    strategySchool: 'Classical Technical',
    category: 'SMART_MONEY',
    categoryLabel: '机构资金 (Smart Money)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Joseph Granville',
    origin: 'Granville New Key to Stock Market Profits (1963)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Granville, Joseph. Granville New Key to Stock Market Profits. Prentice-Hall, 1963.',
    thesis: '成交量走在价格之前（Volume precedes price）。当价格在狭窄区间横盘，而 OBV 能量潮指标率先创出多周新高时，反映主力大资金正在暗中吸筹。',
    description: '经典 OBV 能量潮量先于价走牛策略。',
    requiredData: ['DAILY_OHLCV', 'OBV_SERIES'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [{ id: 'minRvol', name: '放量门槛', type: 'number', default: 1.15, min: 1.0, max: 2.5, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'obv_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'obv_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '良性整理区间 (距高点 < 18%)' },
        { type: 'leaf', id: 'obv_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '放量吸筹脉冲 (RVOL >= 1.15x)' },
        { type: 'leaf', id: 'obv_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.4, label: '蓄势收红小阳 (> 0.4%)' }
      ]
    },
    entry: ['OBV 率先创 20 日新高而价格横盘', 'RVOL >= 1.15x', '日K收红'],
    confirmation: ['次日买入'],
    exit: ['OBV 跌破 20 日均线平仓，或持仓 20 天'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '3.5% 止损', profitTargetRule: '放量波段拉升 8%-12% 止盈', invalidationThreshold: '跌破吸筹平台低点', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'OBV', '能量潮', '主力吸筹', '量价关系'],
    version: '2.0.0'
  },

  // 12. Chaikin Money Flow (CMF) Persistent Inflow
  {
    id: 'cmf_persistent_inflow',
    slug: 'chaikin-money-flow-persistent-inflow',
    name: 'Chaikin Money Flow Persistent Capital Inflow',
    nameZh: '蔡金资金流持续流入',
    nameEn: 'Chaikin Money Flow Persistent Capital Inflow',
    shortName: 'CMF持续流入',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Microstructure & Volume',
    strategySchool: 'Classical Technical',
    category: 'SMART_MONEY',
    categoryLabel: '机构资金 (Smart Money)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Marc Chaikin',
    origin: 'Chaikin Analytics (1980s)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Chaikin, Marc. Technical Analysis of Stocks & Commodities, 1991.',
    thesis: 'CMF 累积 20 日多空成交量在价格极值区间分布。当 CMF 稳定位于 +0.15 以上时，表明买盘持续支配收盘区间，机构净流入极其健康。',
    description: 'Marc Chaikin 经典资金流指标波段持仓模型。',
    requiredData: ['DAILY_OHLCV', 'CMF_20'],
    requiredIndicators: ['changePercent', 'relative_volume', 'rsi'],
    parameters: [{ id: 'minChg', name: '阳线实体(%)', type: 'number', default: 0.5, min: 0.2, max: 2.0, step: 0.1, description: '收红实体' }],
    rules: {
      type: 'group',
      id: 'cmf_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'cmf_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '放量收阳 (> 0.5%)' },
        { type: 'leaf', id: 'cmf_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '资金放量流入 (RVOL >= 1.1x)' },
        { type: 'leaf', id: 'cmf_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 50, max: 70 }, label: '动能强劲健康 (RSI 50-70)' }
      ]
    },
    entry: ['CMF(20) > +0.15', 'RVOL >= 1.1x', '日线收强'],
    confirmation: ['次日买入'],
    exit: ['CMF 跌破 0 轴平仓'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '4.0% 止损', profitTargetRule: '跟踪止盈', invalidationThreshold: '跌破平台低点', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'CMF', '蔡金资金流', '主力流入'],
    version: '2.0.0'
  },

  // 13. Anchored VWAP Multi-Day Defense Rebound
  {
    id: 'vwap_institutional_defense',
    slug: 'anchored-vwap-multi-day-defense',
    name: 'Anchored VWAP Multi-Day Defense Rebound',
    nameZh: '锚定 VWAP 多日波段防御回升',
    nameEn: 'Anchored VWAP Multi-Day Defense Rebound',
    shortName: '锚定VWAP防御',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Microstructure & Volume',
    strategySchool: 'Quantitative Technical',
    category: 'SMART_MONEY',
    categoryLabel: '机构资金 (Smart Money)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Brian Shannon',
    origin: 'Technical Analysis Using Multiple Timeframes (2008)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_lo_mamaysky_wang_2000'],
    sourceReference: 'Shannon, Brian. Technical Analysis Using Multiple Timeframes. Life Cycle Publishing, 2008.',
    thesis: '从前一重要波段低点或财报跳空点锚定的成交量加权平均线（Anchored VWAP），是该事件以来机构所有持仓的平均保本成本线，具备强烈的护盘反弹效应。',
    description: '从关键拐点锚定 VWAP 的波段回踩确认模型。',
    requiredData: ['DAILY_OHLCV', 'ANCHORED_VWAP'],
    requiredIndicators: ['changePercent', 'relative_volume', 'rsi'],
    parameters: [{ id: 'rsiMid', name: 'RSI支撑区', type: 'number', default: 50, min: 40, max: 60, step: 1, description: 'RSI中轴' }],
    rules: {
      type: 'group',
      id: 'avwap_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'av_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.4, label: '支撑位反弹阳线 (> 0.4%)' },
        { type: 'leaf', id: 'av_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '放量护盘承接 (RVOL >= 1.1x)' },
        { type: 'leaf', id: 'av_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 48, max: 65 }, label: '中轴稳健 (RSI 48-65)' }
      ]
    },
    entry: ['价格回踩锚定 VWAP 均线企稳', 'RVOL >= 1.1x', '收阳'],
    confirmation: ['次日买入'],
    exit: ['收盘跌破锚定 VWAP 下方 1.5% 止损，或持有 20 天'],
    rebalance: ['固定风险 1%'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '跌破锚定 VWAP 止损 (约 3.0%-4.0%)', profitTargetRule: '波段前高获利止盈', invalidationThreshold: '跌破锚定 VWAP', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'AVWAP', '锚定均线', '机构成本', '防御反弹'],
    version: '2.0.0'
  },

  // 14. MACD Double Zero-Line Bullish Expansion
  {
    id: 'macd_zero_cross_momentum',
    slug: 'macd-zero-line-bullish-expansion',
    name: 'MACD Double Zero-Line Bullish Expansion',
    nameZh: 'MACD 零轴二次放量上穿',
    nameEn: 'MACD Double Zero-Line Bullish Expansion',
    shortName: 'MACD零轴二次发散',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Gerald Appel',
    origin: 'Technical Analysis: Power Tools for Active Investors (2005)',
    sourceType: 'ORIGINAL_AUTHOR',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Appel, Gerald. Technical Analysis: Power Tools for Active Investors. FT Press, 2005.',
    thesis: 'MACD 快慢线在零轴上方（多头主导区）回踩企稳后再度金叉发散，且柱状图连续扩张，是波段多头加速的主推浪特征。',
    description: 'Gerald Appel 经典 MACD 零轴上方强力共振模型。',
    requiredData: ['DAILY_OHLCV', 'MACD_12_26_9'],
    requiredIndicators: ['macd_histogram', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'minChg', name: '实体涨幅', type: 'number', default: 0.6, min: 0.2, max: 2.0, step: 0.1, description: '阳线实体' }],
    rules: {
      type: 'group',
      id: 'macd_z_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'mz_hist', indicatorId: 'macd_histogram', operator: 'GT', value: 0, label: 'MACD柱线翻红多头动能 (> 0)' },
        { type: 'leaf', id: 'mz_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.6, label: '发散大阳线 (> 0.6%)' },
        { type: 'leaf', id: 'mz_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '放量支持 (RVOL >= 1.15x)' }
      ]
    },
    entry: ['MACD 在零轴上方金叉且柱线翻红', 'RVOL >= 1.15x', '日K阳线 > 0.6%'],
    confirmation: ['次日买入'],
    exit: ['MACD 柱线连续缩短平仓，或持有 20 天'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.0% 止损', profitTargetRule: 'MACD 顶背离或死叉平仓', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'MACD', '零轴金叉', '动能扩张'],
    version: '2.0.0'
  },

  // 15. Dual Relative & Absolute Momentum Swing
  {
    id: 'dual_momentum_swing',
    slug: 'dual-relative-absolute-momentum-swing',
    name: 'Dual Relative & Absolute Momentum Swing',
    nameZh: '相对与绝对双动量波段',
    nameEn: 'Dual Relative & Absolute Momentum Swing',
    shortName: '双动量波段',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Cross-Sectional Momentum',
    strategySchool: 'Academic Factor',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Gary Antonacci / Moskowitz, Ooi & Pedersen',
    origin: 'Dual Momentum Investing (2014) / JFE (2012)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_moskowitz_ooi_pedersen_2012', 'src_jegadeesh_titman_1993'],
    sourceReference: 'Antonacci, Gary. Dual Momentum Investing. McGraw-Hill, 2014.',
    thesis: '同时满足相对动量（截面回报跑赢标普500基准）与绝对动量（自身价格处于自身趋势均线上方），大幅消减熊市单边下行风险，提供极佳的胜率保护。',
    description: '安东纳奇双动量体系波段落地版。',
    requiredData: ['DAILY_OHLCV', 'BENCHMARK_SPY', 'SMA_50'],
    requiredIndicators: ['rs_vs_spy', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'minRs', name: '超额强度(%)', type: 'number', default: 2.0, min: 0.5, max: 6.0, step: 0.5, description: '相对标普超额' }],
    rules: {
      type: 'group',
      id: 'dm_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'dm_rs', indicatorId: 'rs_vs_spy', operator: 'GTE', value: 2.0, label: '相对标普超额动能 (RS >= +2.0%)' },
        { type: 'leaf', id: 'dm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.4, label: '绝对动能收红 (> 0.4%)' },
        { type: 'leaf', id: 'dm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.1, label: '健康流动性 (RVOL >= 1.1x)' }
      ]
    },
    entry: ['相对 SPY 强弱 RS >= 2%', '绝对价格站上 SMA 50', '放量小长阳'],
    confirmation: ['次日买入'],
    exit: ['相对强弱跌破 SPY 或跌破 SMA 50 离场'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.0% 止损', profitTargetRule: '跟踪相对动能减弱止盈', invalidationThreshold: '跌破 SMA 50', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A+', '双动量', '相对强弱', '绝对动量'],
    version: '2.0.0'
  },

  // 16. Sector Relative Strength Rotation
  {
    id: 'sector_rs_rotation',
    slug: 'sector-relative-strength-rotation',
    name: 'Sector Relative Strength Momentum Rotation',
    nameZh: '板块相对强弱领先轮动',
    nameEn: 'Sector Relative Strength Momentum Rotation',
    shortName: '板块相对强弱轮动',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Cross-Sectional Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'John Murphy',
    origin: 'Intermarket Analysis (2004)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_jegadeesh_titman_1993'],
    sourceReference: 'Murphy, John J. Intermarket Analysis: Profiting from Global Market Relationships. Wiley, 2004.',
    thesis: '美股行情呈现极强的行业板块轮动规律。筛选全市场排名前 3 的领涨行业 ETF 中的龙头龙头股，享受板块贝塔与个股阿尔法的共振。',
    description: '行业板块相对强度领先轮动策略。',
    requiredData: ['DAILY_OHLCV', 'SECTOR_ETF_DATA'],
    requiredIndicators: ['distFrom52wHigh', 'relative_volume', 'changePercent'],
    parameters: [{ id: 'distTolerance', name: '距新高距离(%)', type: 'number', default: -12, min: -20, max: -3, step: 1, description: '强势度' }],
    rules: {
      type: 'group',
      id: 'sec_rs_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'srs_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '领涨行业龙头标的 (距高点 < 12%)' },
        { type: 'leaf', id: 'srs_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '板块共振长阳 (> 0.5%)' },
        { type: 'leaf', id: 'srs_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '放量建仓 (RVOL >= 1.15x)' }
      ]
    },
    entry: ['属于领涨行业龙头', '距 52 周新高 < 12%', '放量突破'],
    confirmation: ['次日买入'],
    exit: ['板块相对强弱跌出前 3 或持仓 20 天'],
    rebalance: ['等权多头配置'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.5% 止损', profitTargetRule: '板块轮动减弱时离场', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '板块轮动', '行业动量', '相对强弱'],
    version: '2.0.0'
  },

  // 17. Detrended Price Oscillator Cycle Reversal
  {
    id: 'dpo_detrended_osc',
    slug: 'dpo-cycle-swing-reversal',
    name: 'Detrended Price Oscillator Cycle Reversal',
    nameZh: 'DPO 周期摆动波段反转',
    nameEn: 'Detrended Price Oscillator Cycle Reversal',
    shortName: 'DPO周期摆动',
    mode: 'SWING',
    holdingPeriod: '5-15 Trading Days',
    holdingPeriodLabel: '波段 5-15天',
    strategyFamily: 'Short-Term Reversal',
    strategySchool: 'Classical Technical',
    category: 'MEAN_REVERSION',
    categoryLabel: '均值回归 (Mean Reversion)',
    family: 'swing',
    horizon: '5-15 Trading Days',
    direction: 'LONG',
    author: 'Joe DiNapoli',
    origin: 'DiNapoli Levels (1998)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_lehmann_1990'],
    sourceReference: 'DiNapoli, Joe. DiNapoli Levels. Coast Investment Software, 1998.',
    thesis: '去趋势价格振荡器 (DPO) 通过消除长周期趋势影响，准确分离 20-30 个交易日的循环周期，在周期底部低吸捕获下一波段上推。',
    description: '周期波长去趋势振荡波段低吸模型。',
    requiredData: ['DAILY_OHLCV', 'DPO_20'],
    requiredIndicators: ['rsi', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'rsiBound', name: 'RSI过滤', type: 'number', default: 38, min: 25, max: 45, step: 1, description: '低位线' }],
    rules: {
      type: 'group',
      id: 'dpo_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'dpo_rsi', indicatorId: 'rsi', operator: 'LTE', value: 38, label: '周期处于低位 (RSI <= 38)' },
        { type: 'leaf', id: 'dpo_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.3, label: '周期拐头收阳 (> 0.3%)' },
        { type: 'leaf', id: 'dpo_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.05, label: '正常流动性 (RVOL >= 1.05x)' }
      ]
    },
    entry: ['DPO 在低位形成双底拐头', 'RSI <= 38', '收盘小阳'],
    confirmation: ['次日买入'],
    exit: ['DPO 运行至周期高点或持仓 15 天退出'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '3.5% 止损', profitTargetRule: '周期上推 6%-8% 止盈', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 15 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', 'DPO', '周期', '均值回归'],
    version: '2.0.0'
  },

  // 18. Chaikin Volatility Surge Breakout
  {
    id: 'chaikin_volatility_surge',
    slug: 'chaikin-volatility-surge-breakout',
    name: 'Chaikin Volatility Expansion Breakout',
    nameZh: '蔡金波动率放量爆发',
    nameEn: 'Chaikin Volatility Expansion Breakout',
    shortName: '蔡金波动率爆发',
    mode: 'SWING',
    holdingPeriod: '5-15 Trading Days',
    holdingPeriodLabel: '波段 5-15天',
    strategyFamily: 'Technical Pattern Recognition',
    strategySchool: 'Classical Technical',
    category: 'BREAKOUT',
    categoryLabel: '通道突破 (Breakout)',
    family: 'swing',
    horizon: '5-15 Trading Days',
    direction: 'LONG',
    author: 'Marc Chaikin',
    origin: 'Technical Analysis of Stocks & Commodities (1991)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'C',
    evidenceType: 'PRACTITIONER_CLASSIC',
    canonicalSources: ['src_wilder_1978'],
    sourceReference: 'Chaikin, Marc. TASC, 1991.',
    thesis: '计算最高价与最低价差值的 EMA 变化率。当波动率在低位盘整后产生急剧扩张斜率，预示盘局结束并形成新的波段方向。',
    description: '基于蔡金高低波幅扩张的波段爆发跟踪策略。',
    requiredData: ['DAILY_OHLCV', 'CHAIKIN_VOLATILITY_10'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [{ id: 'minRvol', name: '突破放量', type: 'number', default: 1.25, min: 1.0, max: 2.5, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'chaikin_v_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'cv_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '形态优良 (距高点 < 18%)' },
        { type: 'leaf', id: 'cv_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.6, label: '波动率放量扩张阳线 (> 0.6%)' },
        { type: 'leaf', id: 'cv_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.25, label: '放量倍数 (RVOL >= 1.25x)' }
      ]
    },
    entry: ['波动率急剧转正扩张', 'RVOL >= 1.25x', '日线收阳'],
    confirmation: ['次日买入'],
    exit: ['波动率达到极高位见顶或持仓 15 天退出'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '3.5% 止损', profitTargetRule: '跟踪止盈', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 15 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '蔡金', '波动率', '突破'],
    version: '2.0.0'
  },

  // 19. Gatev Pairs Trading Cointegration Residual Reversion
  {
    id: 'pairs_trading_cointegration',
    slug: 'gatev-pairs-trading-cointegration',
    name: 'Gatev Cointegration Pairs Residual Reversion',
    nameZh: '经典配对协整残差回归',
    nameEn: 'Gatev Cointegration Pairs Residual Reversion',
    shortName: '配对协整残差回归',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Pairs Trading',
    strategySchool: 'Academic Factor',
    category: 'STAT_ARB',
    categoryLabel: '统计套利 (Stat Arb)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Evan Gatev, William Goetzmann & Geert Rouwenhorst',
    origin: 'The Review of Financial Studies (2006)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_gatev_goetzmann_rouwenhorst_2006'],
    sourceReference: 'Gatev, Evan, William N. Goetzmann, and K. Geert Rouwenhorst. The Review of Financial Studies 19.3 (2006): 797-827.',
    thesis: '同行业或高度相关资产对的价差具有平稳协整特征。当标准化价差偏离超过 2 倍历史标准差时，未来 5-20 个交易日残差有 85% 以上概率收敛至均值。',
    description: 'RFS 顶级金融学期刊配对交易金标准。寻找同行业中发生非理性临时偏离的超跌端做多。',
    requiredData: ['DAILY_OHLCV', 'PEER_SPREAD_ZSCORE'],
    requiredIndicators: ['rsi', 'relative_volume', 'changePercent'],
    parameters: [{ id: 'rsiLow', name: '偏离端超跌过滤', type: 'number', default: 35, min: 20, max: 45, step: 1, description: '超跌线' }],
    rules: {
      type: 'group',
      id: 'pairs_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'pr_rsi', indicatorId: 'rsi', operator: 'LTE', value: 35, label: '相对价差超跌极值 (RSI <= 35)' },
        { type: 'leaf', id: 'pr_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.2, label: '企稳收红 (> 0.2%)' },
        { type: 'leaf', id: 'pr_vol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '充沛套利流动性 (RVOL >= 1.0x)' }
      ]
    },
    entry: ['价差 Z-Score < -2.0', '多头端企稳收红', '流动性充沛'],
    confirmation: ['次日买入'],
    exit: ['价差回归至均值 0 轴平仓，或持有 20 天'],
    rebalance: ['配对中性或单边纯多头执行'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '价差进一步扩散至 3.5 倍标准差硬止损', profitTargetRule: '价差完全收敛至 0 均值', invalidationThreshold: '价差扩散超过 3.5 标差', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Gatev et al. (2006) RFS',
      empiricalFindings: 'Demonstrated 11% annualized excess returns on daily CRSP equity pairs over a 40-year sample period.'
    },
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A+', '配对交易', '协整', '统计套利'],
    version: '2.0.0'
  },

  // 20. Dual-Class Share & ADR Spread Mean Reversion
  {
    id: 'dual_class_spread_convergence',
    slug: 'dual-class-adr-spread-convergence',
    name: 'Dual-Class Share & ADR Spread Mean Reversion',
    nameZh: '双重股权与 ADR 价差收敛',
    nameEn: 'Dual-Class Share & ADR Spread Mean Reversion',
    shortName: '双重股权价差收敛',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Statistical Arbitrage',
    strategySchool: 'Academic Factor',
    category: 'STAT_ARB',
    categoryLabel: '统计套利 (Stat Arb)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Evan Gatev et al.',
    origin: 'Pairs Trading / Dual-Class Asset Pricing Literature',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_gatev_goetzmann_rouwenhorst_2006'],
    sourceReference: 'Gatev, Evan, et al. The Review of Financial Studies (2006).',
    thesis: '相同基础经济利益资产（如 GOOGL vs GOOG，或美股 ADR 与母股）之间的短期价差由流动性冲击产生，具备坚实的经济学套利收敛边界。',
    description: '双重股权（Class A vs Class C）及跨市场对应标的价差波段收敛套利。',
    requiredData: ['DAILY_OHLCV', 'DUAL_CLASS_SPREAD'],
    requiredIndicators: ['rsi', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'rsiLow', name: '相对低位', type: 'number', default: 38, min: 25, max: 45, step: 1, description: '折价端过滤' }],
    rules: {
      type: 'group',
      id: 'dual_class_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'dc_rsi', indicatorId: 'rsi', operator: 'LTE', value: 38, label: '折价端处于超跌位 (RSI <= 38)' },
        { type: 'leaf', id: 'dc_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.1, label: '折价收敛企稳 (> 0.1%)' },
        { type: 'leaf', id: 'dc_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.0, label: '流动性充沛 (RVOL >= 1.0x)' }
      ]
    },
    entry: ['价差偏离达到历史 95% 极端分位', '折价端企稳收红'],
    confirmation: ['次日买入'],
    exit: ['价差收敛至历史中枢平仓'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '3.0% 止损', profitTargetRule: '价差完全收敛', invalidationThreshold: '价差进一步扩大', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 30000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A', '双重股权', 'ADR', '统计套利'],
    version: '2.0.0'
  },

  // 21. Supply Chain Lead-Lag Momentum Propagation
  {
    id: 'lead_lag_cross_asset',
    slug: 'supply-chain-lead-lag-momentum',
    name: 'Supply Chain Lead-Lag Momentum Propagation',
    nameZh: '产业供应链领先滞后传导',
    nameEn: 'Supply Chain Lead-Lag Momentum Propagation',
    shortName: '供应链动能传导',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Cross-Sectional Momentum',
    strategySchool: 'Academic Factor',
    category: 'STAT_ARB',
    categoryLabel: '统计套利 (Stat Arb)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Bruno Biais & Pierre Hillion / Cohen & Frazzini',
    origin: 'Economic Links and Predictable Returns (Journal of Finance 2008)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_jegadeesh_titman_1993'],
    sourceReference: 'Cohen, Lauren, and Andrea Frazzini. Economic Links and Predictable Returns. The Journal of Finance 63.4 (2008): 1977-2011.',
    thesis: '大客户核心股票股价发生重大突破后，由于市场认知有限性，其主要供应商与核心产业链企业股价呈现 1-4 周的滞后跟随传导。',
    description: '基于学术期刊证实的核心上下游客户供应链动能领先滞后传导波段策略。',
    requiredData: ['DAILY_OHLCV', 'SUPPLY_CHAIN_MAPPING'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [{ id: 'minRvol', name: '启动放量', type: 'number', default: 1.2, min: 1.0, max: 2.5, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'lead_lag_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'll_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -18, label: '形态优良整理 (距高点 < 18%)' },
        { type: 'leaf', id: 'll_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.5, label: '传导发动阳线 (> 0.5%)' },
        { type: 'leaf', id: 'll_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.2, label: '放量跟进 (RVOL >= 1.2x)' }
      ]
    },
    entry: ['上游核心客户发生 20 日突破', '滞后供应商日K放量突破', 'RVOL >= 1.2x'],
    confirmation: ['次日买入'],
    exit: ['波段跟随完成获利 8%-12% 离场，或持有 20 天'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '3.5% 止损', profitTargetRule: '跟随传导幅度止盈', invalidationThreshold: '跌破前低', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A', '供应链', '领先滞后', '动能传导'],
    version: '2.0.0'
  },

  // 22. Ball-Brown Post-Earnings 30-Day Drift
  {
    id: 'pead_medium_drift',
    slug: 'ball-brown-post-earnings-medium-drift',
    name: 'Ball-Brown Post-Earnings 30-Day Drift',
    nameZh: '鲍尔-布朗财报后波段漂移',
    nameEn: 'Ball-Brown Post-Earnings 30-Day Drift',
    shortName: '财报中波段漂移',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Post-Earnings Announcement Drift',
    strategySchool: 'Academic Factor',
    category: 'FACTOR',
    categoryLabel: '多因子 (Factor)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Ray Ball & Philip Brown',
    origin: 'Journal of Accounting Research (1968)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_ball_brown_1968'],
    sourceReference: 'Ball, Ray, and Philip Brown. Journal of Accounting Research (1968).',
    thesis: '超预期财报公告后的正向收益漂移在公告后 2–4 周表现最为坚韧，通过剔除一次性非经常收益，筛选高营收与经营现金流支撑的个股波段持股。',
    description: '财报超预期后的 2-4 周波段单边漂移策略。',
    requiredData: ['DAILY_OHLCV', 'EARNINGS_ANNOUNCEMENT'],
    requiredIndicators: ['changePercent', 'relative_volume', 'distFrom52wHigh'],
    parameters: [{ id: 'minRvol', name: '放量维持', type: 'number', default: 1.15, min: 1.0, max: 2.5, step: 0.1, description: '放量' }],
    rules: {
      type: 'group',
      id: 'pead_m_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'pm_dist', indicatorId: 'distFrom52wHigh', operator: 'GTE', value: -12, label: '保持在高位区域 (距高点 < 12%)' },
        { type: 'leaf', id: 'pm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.4, label: '漂移趋势中阳线 (> 0.4%)' },
        { type: 'leaf', id: 'pm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '资金持续流入 (RVOL >= 1.15x)' }
      ]
    },
    entry: ['财报超预期后首次旗形整理突破', 'RVOL >= 1.15x', '距高点 < 12%'],
    confirmation: ['次日买入'],
    exit: ['持仓 20 天离场，或跌破启动阳线底部'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '4.0% 止损', profitTargetRule: '8%-12% 目标获利离场', invalidationThreshold: '跌破整理平台下沿', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 20000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A+', 'PEAD', '财报漂移', '动能'],
    version: '2.0.0'
  },

  // 23. Multiple Moving Average Ribbon Bullish Flare
  {
    id: 'ma_ribbon_expansion',
    slug: 'multiple-moving-average-ribbon-flare',
    name: 'Multiple Moving Average Ribbon Bullish Flare',
    nameZh: '顾比均线复合多头发散',
    nameEn: 'Multiple Moving Average Ribbon Bullish Flare',
    shortName: '顾比均线多头发散',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Classical Technical',
    category: 'TREND',
    categoryLabel: '趋势跟踪 (Trend Following)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Daryl Guppy',
    origin: 'Trend Trading (2004)',
    sourceType: 'ESTABLISHED_PRACTITIONER',
    evidenceLevel: 'B',
    evidenceType: 'INDUSTRY_EMPIRICAL',
    canonicalSources: ['src_brock_lakonishok_lebaron_1992'],
    sourceReference: 'Guppy, Daryl. Trend Trading. John Wiley & Sons, 2004.',
    thesis: '短期交易者均线组（EMA 3, 5, 8, 10, 12, 15）与长期投资者均线组（EMA 30, 35, 40, 45, 50, 60）同步扩张发散，表明多空周期产生完美共振。',
    description: '顾比复合移动平均线 (GMMA) 长期投资者与短期交易者双向发散波段模型。',
    requiredData: ['DAILY_OHLCV', 'GMMA_RIBBON'],
    requiredIndicators: ['changePercent', 'relative_volume', 'rsi'],
    parameters: [{ id: 'minChg', name: '发散实体涨幅', type: 'number', default: 0.6, min: 0.2, max: 2.0, step: 0.1, description: '阳线实体' }],
    rules: {
      type: 'group',
      id: 'gmma_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'gm_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.6, label: '双组均线发散阳线 (> 0.6%)' },
        { type: 'leaf', id: 'gm_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '发散放量 (RVOL >= 1.15x)' },
        { type: 'leaf', id: 'gm_rsi', indicatorId: 'rsi', operator: 'BETWEEN', value: { min: 52, max: 68 }, label: '动能健康 (RSI 52-68)' }
      ]
    },
    entry: ['短期均线组整体上穿长期均线组', '长期均线组开始多头发散', '放量收阳'],
    confirmation: ['次日买入'],
    exit: ['短期均线组向下载入长期均线组平仓'],
    rebalance: ['按 1% 净值风险分配头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '以长期均线组上沿为止损线 (约 3.5%-4.5%)', profitTargetRule: '移动跟踪止盈', invalidationThreshold: '跌破长期均线组', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 15000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    defaultTimeframes: ['1D'],
    tags: ['波段', '顾比均线', 'GMMA', '均线带', '趋势共振'],
    version: '2.0.0'
  },

  // 24. Market Regime Filtered Trend Initiation
  {
    id: 'regime_filtered_trend',
    slug: 'market-regime-filtered-trend-initiation',
    name: 'Market Regime Filtered Trend Initiation',
    nameZh: '大盘宏观状态过滤趋势启动',
    nameEn: 'Market Regime Filtered Trend Initiation',
    shortName: '宏观状态过滤趋势',
    mode: 'SWING',
    holdingPeriod: '5-20 Trading Days',
    holdingPeriodLabel: '波段 5-20天',
    strategyFamily: 'Time-Series Momentum',
    strategySchool: 'Academic Factor',
    category: 'MACRO_REGIME',
    categoryLabel: '宏观模型 (Macro Regime)',
    family: 'swing',
    horizon: '5-20 Trading Days',
    direction: 'LONG',
    author: 'Tobias Moskowitz, Yao Hua Ooi & Lasse Pedersen',
    origin: 'Time Series Momentum (JFE 2012)',
    sourceType: 'ACADEMIC_RESEARCH',
    evidenceLevel: 'A+',
    evidenceType: 'ACADEMIC_PEER_REVIEWED',
    canonicalSources: ['src_moskowitz_ooi_pedersen_2012'],
    sourceReference: 'Moskowitz, Tobias J., Yao Hua Ooi, and Lasse Heje Pedersen. Journal of Financial Economics (2012).',
    thesis: '在标普 500 处于 RISK_ON（位于 200 SMA 之上且 VIX 处于低位）的大盘安全宏观环境下执行个股突破，成功率显著高于中性与防守环境。',
    description: '大盘宏观环境驱动的自适应波段突破模型。',
    requiredData: ['DAILY_OHLCV', 'MARKET_REGIME_CONTEXT'],
    requiredIndicators: ['market_regime', 'changePercent', 'relative_volume'],
    parameters: [{ id: 'minChg', name: '突破实体', type: 'number', default: 0.6, min: 0.2, max: 2.0, step: 0.1, description: '涨幅' }],
    rules: {
      type: 'group',
      id: 'regime_tr_root',
      logicalOperator: 'AND',
      children: [
        { type: 'leaf', id: 'rg_state', indicatorId: 'market_regime', operator: 'EQ', value: 'RISK_ON', label: '宏观大盘处于 RISK_ON 顺风环境' },
        { type: 'leaf', id: 'rg_chg', indicatorId: 'changePercent', operator: 'GT', value: 0.6, label: '顺势爆发阳线 (> 0.6%)' },
        { type: 'leaf', id: 'rg_rvol', indicatorId: 'relative_volume', operator: 'GTE', value: 1.15, label: '放量支持 (RVOL >= 1.15x)' }
      ]
    },
    entry: ['大盘宏观判定为 RISK_ON', '个股放量突破 20 日高点', 'RVOL >= 1.15x'],
    confirmation: ['次日买入'],
    exit: ['大盘转入 RISK_OFF 或个股破位 20 均线平仓'],
    rebalance: ['等权头寸'],
    riskModel: { maxRiskPerTradePercent: 1.0, stopLossRule: '固定 4.0% 止损', profitTargetRule: '宏观环境恶化或跌破均线止盈', invalidationThreshold: '大盘宏观转入 RISK_OFF', maxHoldingPeriodBars: 20 },
    antiLookaheadRules: ['次日开盘进场'],
    transactionCostModel: { commissionRatePercent: 0.05, slippageRatePercent: 0.05, minimumLiquidityDailyDollar: 25000000 },
    backtestConfig: { defaultUniverse: 'SP500', benchmark: 'SPY', lookbackDays: 504, recommendedTimeframe: '1D' },
    status: 'ACTIVE',
    literatureEvidence: {
      reference: 'Moskowitz et al. (2012) JFE',
      empiricalFindings: 'Proved equity trend-following strategies generate significantly higher Sharpe ratio when conditional on risk-on macro regime.'
    },
    defaultTimeframes: ['1D'],
    tags: ['波段', '学术A+', '宏观状态', 'RISK_ON', '趋势过滤'],
    version: '2.0.0'
  }
];
